juspay/hyperswitch-control-center

- src/components/CustomCharts/FunnelChart.res
- src/entryPoints/hyperswitch/SidebarValues.res
- src/screens/HyperSwitch/Analytics/Analytics.res
- src/screens/HyperSwitch/Analytics/UserAnalytics/UserJourneyAnalyticsEntity.res
- src/screens/HyperSwitch/PaymentLogs/PaymentLogs.res
- src/utils/LogicUtils.res
Fixes for User Journey Analytics
> Fixes for User Journey Analytics

- src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
switch merchant dropdown to headless ui menu component replacement 
make dashboard component UI look bit better 
by enabling feature flag called `switch_merchant` in `FeatureFlag.json` file
> switch merchant ui changes

- src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/IntegrateFromScratch.res
- src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/MigrateFromStripe.res
Shows 'Complete' at the last step
> back button

- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/entryPoints/hyperswitch/Provider/GlobalProvider.res
- src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
- src/screens/HyperSwitch/Connectors/ConnectorAccountDetailsHelper.res
- src/screens/HyperSwitch/Connectors/ConnectorUIUtils/PaymentMethod.res
- src/screens/HyperSwitch/Connectors/ConnectorUtils.res
- src/screens/HyperSwitch/HSMixPanel.res
- src/screens/HyperSwitch/Home/HomeV2.res
- src/screens/HyperSwitch/Home/QuickStart/TestPayment.res
- src/screens/HyperSwitch/Routing/RoutingConfigure.res
- src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
- src/screens/HyperSwitch/RoutingRevamp/Previewers/RulePreviewer.res
- src/screens/HyperSwitch/SDKPayment/Payment.res
- src/screens/HyperSwitch/SDKPayment/WebSDK.res
- src/screens/HyperSwitch/Settings/BusinessMapping/BusinessMapping.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchAuthUtils.res
- src/utils/HSwitchGlobalVars.res
- Bug fixes
- Removed default Fallback selection from rule based routing 
- Added connector Label
> Removed Default Processor for rule based + Bug fixes

- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/entryPoints/hyperswitch/SidebarValues.res
- src/screens/HyperSwitch/Utils/HSwitchGlobalSearchBar.res
> system metrics changes

- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/screens/HyperSwitch/Utils/HSwitchGlobalSearchBar.res
> fixed search bar issue + Uncommented searchbar

- src/screens/HyperSwitch/SDKPayment/SDKPage.res
- src/screens/HyperSwitch/SDKPayment/SDKPaymentTypes.res
- src/screens/HyperSwitch/SDKPayment/SDKPaymentUtils.res
> Changed Amount field from text field to number field

- src/screens/HyperSwitch/Home/HomeV2.res
- tailwindHyperSwitch.config.js
Merchant account failing for old users
> Bugfix: Merchant account failing - Merchant account failing for old users

- .github/workflows/release-new-version.yml
> feat: update release github action

- .github/workflows/pr-title-spell-check.yml
- .github/workflows/release-new-version.yml
- src/screens/HyperSwitch/Connectors/ConnectorList.res
ConnectorList for live updated
> Fix: ConnectorList for live updated 

- .github/workflows/release-new-version.yml
> chore: Release new version workflow fixes

- src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/CheckoutHelper.res
> fix: default card layout

- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/entryPoints/hyperswitch/HyperSwitchEntry.res
- src/entryPoints/hyperswitch/HyperswitchAtom.res
- src/screens/HyperSwitch/Analytics/Analytics.res
- src/screens/HyperSwitch/Analytics/HomePageOverview/HomePageOverviewComponent.res
- src/screens/HyperSwitch/Analytics/PaymentsAnalytics/PaymentAnalytics.res
- src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
- src/screens/HyperSwitch/Connectors/ConnectorAccountDetailsHelper.res
- src/screens/HyperSwitch/Connectors/ConnectorList.res
- src/screens/HyperSwitch/Connectors/ConnectorPreview.res
- src/screens/HyperSwitch/Disputes/Disputes.res
- src/screens/HyperSwitch/FraudAndRisk/FRMConfigure.res
- src/screens/HyperSwitch/FraudAndRisk/FRMIntegrationFields.res
- src/screens/HyperSwitch/HSMixPanel.res
- src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
- src/screens/HyperSwitch/Home/HomeUtils.res
- src/screens/HyperSwitch/Home/HomeV2.res
- src/screens/HyperSwitch/Order/OrderUIUtils.res
- src/screens/HyperSwitch/Order/Orders.res
- src/screens/HyperSwitch/Order/ShowOrder.res
- src/screens/HyperSwitch/Refunds/Refund.res
- src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
- src/screens/HyperSwitch/Settings/HSwitchSettings.res
- src/screens/HyperSwitch/Utils/HSwitchGlobalSearchBar.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchAuthScreen.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchAuthUtils.res
> fix: Recoil value for feature flag updated

- src/screens/HyperSwitch/SDKPayment/TestPayment.res
> fix: SDK Processing - Go to payments not working fix

- src/screens/HyperSwitch/Home/CommonConnectorFlow/ConfigureConnector.res
- src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
- src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
> fix: connector label  and profile id default value fix

- src/entryPoints/hyperswitch/SidebarValues.res
- src/screens/HyperSwitch/Order/OrderEntity.res
- src/screens/HyperSwitch/Order/OrderTypes.res
- src/screens/HyperSwitch/Order/ShowOrder.res
- src/screens/HyperSwitch/SDKPayment/TestCredentials.res
> feat: Show Orders Enhancements & sidebar value changes

- src/entryPoints/hyperswitch/HyperSwitchApp.res
> feat: add scrollbar and white space scrollable

- src/entryPoints/hyperswitch/HyperSwitchApp.res
> fix: Connector UI Issue.

- src/screens/HyperSwitch/APIUtils/APIUtils.res
- src/screens/HyperSwitch/Home/HomeUtils.res
- src/screens/HyperSwitch/Sidebar/Sidebar.res
> fix: Signout API removed.

- src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
- src/screens/HyperSwitch/RoutingRevamp/Previewers/RulePreviewer.res
> fix: metadata field issue fix

- src/screens/HyperSwitch/Analytics/Analytics.res
- src/screens/HyperSwitch/Analytics/DownloadReportModal.res
- src/screens/HyperSwitch/Analytics/PaymentsAnalytics/PaymentAnalytics.res
- src/screens/HyperSwitch/Analytics/RefundsAnalytics/RefundsAnalytics.res
> fix: refunds reports end point change

- src/screens/HyperSwitch/APIUtils/APIUtils.res
- src/screens/HyperSwitch/APIUtils/APIUtilsTypes.res
- src/screens/HyperSwitch/UserManagement/ShowUserData.res
> feat: Resend Invite Removal

- src/screens/HyperSwitch/UserManagement/UserRoleEntry.res
Disabled button
Waiting for api fix
> fix: disable-user-invite-button

- src/screens/HyperSwitch/Sidebar/Sidebar.res
> feat: Sidebar expansion close

- src/components/TableUtils.res
- src/screens/HyperSwitch/APIUtils/APIUtils.res
- src/screens/HyperSwitch/HSwitchUtils.res
- src/screens/HyperSwitch/Order/OrderEntity.res
- src/screens/HyperSwitch/Sidebar/Sidebar.res
- src/screens/HyperSwitch/UserManagement/UserRoleEntry.res
> feat: Table wrap changes & sidebar version removed

- README.md
> feat: README.md PR title changes

- src/screens/HyperSwitch/APIUtils/APIUtils.res
- src/screens/HyperSwitch/APIUtils/APIUtilsTypes.res
> fix: APIUtils changes

- public/hyperswitch/icons/solid.svg
- src/screens/HyperSwitch/APIUtils/APIUtils.res
> fix: API fix and radio icon changes

- src/screens/HyperSwitch/Analytics/Analytics.res
- src/screens/HyperSwitch/Analytics/SystemMetrics/SystemMetricsAnalytics.res
- src/screens/HyperSwitch/Analytics/UserAnalytics/UserJourneyAnalytics.res
- src/screens/HyperSwitch/Connectors/ConnectorList.res
- src/screens/HyperSwitch/Developer/APIKeys/KeyManagement.res
- src/screens/HyperSwitch/HSwitchUtils.res
- src/screens/HyperSwitch/Refunds/Refund.res
- src/screens/HyperSwitch/Routing/RoutingStack.res
> fix: Page scroll issue fix and connector card css fix

- src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
- src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
- src/screens/HyperSwitch/StripePlusPaypal/StripePlusPaypalUIUtils.res
> fix: Stripe Paypal Profile Issue

- src/components/AdvancedSearchComponent.res
- src/components/DynamicSingleStat.res
- src/components/SelectModal.res
- src/hooks/TimeZoneHook.res
- src/screens/HyperSwitch/Routing/VolumeSplitRouting.res
- webpack.prod.js
> fix: Removed console log form prod

- src/screens/HyperSwitch/APIUtils/APIUtils.res
> fix: verify email url fix

- src/screens/HyperSwitch/UserManagement/UserRoleEntry.res
> fix: Enabled invite users

- src/screens/HyperSwitch/Connectors/ConnectorPreview.res
- src/screens/HyperSwitch/Connectors/ConnectorTableUtils.res
> fix: connnector status UI changes

- src/components/TableUtils.res
> fix: Text overlap issue fix

- tailwindHyperSwitch.config.js
> fix: Scrollbar revert

- src/screens/HyperSwitch/Settings/BusinessMapping/BusinessProfile.res
> fix: business profile addition modal bugfix

- src/screens/HyperSwitch/Home/HomeUtils.res
- src/screens/HyperSwitch/Order/Orders.res
> fix: Unnecessary API List count of connectors stop

- src/screens/HyperSwitch/Connectors/ConnectorUtils.res
> fix: Enabled braintree in prod

- src/screens/HyperSwitch/APIUtils/APIUtils.res
> fix: disputes api change

- src/entryPoints/hyperswitch/SidebarValues.res
> fix: Connector list fix for search live

- src/screens/HyperSwitch/APIUtils/APIUtils.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
> fix: email issue in mixpanel capture

- docs/CODE_OF_CONDUCT.md
- docs/SECURITY.md
> docs: added security policy, code of conduct and contributing md files

- LICENSE
- README.md
- docs/CONTRIBUTING.md
Added licences and contributing guidelines.
> docs: added license file and contributing guidelines

- src/components/CustomCharts/HighchartHorizontalBarChart.res
- src/components/CustomExpandableTable.res
- src/components/DynamicSingleStat.res
- src/components/FilterUtils.res
- src/components/LoadedTable.res
- src/components/ReactWindowTable.res
- src/components/SelectBox.res
- src/components/Table.res
- src/components/form/FormRenderer.res
- src/components/form/MultipleTextInput.res
- src/components/form/NumericTextInput.res
- src/context/ChartContext.res
- src/context/FilterContext.res
- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/hooks/OutsideClick.res
- src/hooks/QueryHook.res
- src/libraries/LocalStorage.res
- src/screens/HyperSwitch/Connectors/ConnectorAccountDetailsHelper.res
- src/screens/HyperSwitch/Connectors/ConnectorHome.res
- src/screens/HyperSwitch/Connectors/ConnectorUtils.res
- src/screens/HyperSwitch/Helpers/HelperComponents.res
- src/screens/HyperSwitch/Home/HomeV2.res
- src/screens/HyperSwitch/Order/ShowOrder.res
- src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
- src/screens/HyperSwitch/Surcharge/Surcharge.res
- src/screens/HyperSwitch/Surcharge/SurchargeUtils.res
- src/screens/componentsDemo/CardTable.res
- src/utils/LogicUtils.res
> chore: Array changes

- config/FeatureFlag.json
- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/HSwitchAgreementScreen.res
- src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/ProdOnboardingLanding.res
- src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
> fix: Switch merchant enabled for Live Env

- src/screens/HyperSwitch/Connectors/ConnectorPreview.res
- src/screens/HyperSwitch/Connectors/ConnectorTableUtils.res
> fix: connector integration status and disabled ui change

- src/components/CustomCharts/HighchartTimeSeriesChart.res
- src/components/CustomCharts/LineChartUtils.res
- src/components/DynamicChart.res
- src/components/DynamicSingleStat.res
- src/components/DynamicTable.res
- src/components/HSwitchSingleStatWidget.res
- src/components/RemoteFiltersUtils.res
- src/components/SelectBox.res
- src/components/SelectBox.resi
- src/components/SingleStats/SingleStatEntity.res
- src/context/FilterContext.res
- src/context/SingleStatContext.res
- src/entities/analytics/AnalyticsUtils.res
- src/hooks/AnalyticsHooks.res
- src/hooks/QueryHook.res
- src/libraries/Highcharts.res
- src/screens/HyperSwitch/Analytics/Analytics.res
- src/screens/HyperSwitch/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
- src/screens/HyperSwitch/Analytics/SystemMetrics/SystemMetricsAnalytics.res
- src/utils/TimeZoneConversion.res
> chore: analytics files Js.Dict -> Dict migration

- .github/workflows/eslint-check.yml
- src/components/form/TextInput.res
- src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
Fix Eslint Issue and update eslint github action workflow
> fix: eslint issue

- src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
> feat: Modal added for Switch merchant switch.

- src/screens/HyperSwitch/Order/OrderEntity.res
- src/screens/HyperSwitch/Order/OrderTypes.res
- src/screens/HyperSwitch/Order/ShowOrder.res
> feat: Connector Label added in Show Payments

- src/screens/HyperSwitch/Home/CommonConnectorFlow/ConfigureConnector.res
- src/screens/HyperSwitch/Home/CommonConnectorFlow/QuickStartConnectorFlow.res
- src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
- src/screens/HyperSwitch/Home/QuickStart/GoLive.res
- src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/IntegrateYourAppLanding.res
- src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/MigrateFromStripe.res
> feat: mixpanel added for quick start flow

- src/screens/HyperSwitch/Order/OrderEntity.res
- src/screens/HyperSwitch/Order/ShowOrder.res
- src/utils/LogicUtils.res
> fix: show billing and shipping address

- src/screens/HyperSwitch/Order/ShowOrder.res
- src/screens/HyperSwitch/Routing/PriorityRouting.res
- src/screens/HyperSwitch/Routing/VolumeSplitRouting.res
- src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
- src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUtils.res
- src/screens/HyperSwitch/RoutingRevamp/BasicDetailsForm.res
> fix: profile changes in Routing

- README.md
- config/FeatureFlag.json
- src/entryPoints/hyperswitch/FeatureFlagUtils.res
- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/entryPoints/hyperswitch/SidebarValues.res
> fix: customer module flag removal

- README.md
- config/FeatureFlag.json
- src/entryPoints/hyperswitch/FeatureFlagUtils.res
- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/entryPoints/hyperswitch/SidebarValues.res
Reverts juspay/hyperswitch-control-center#242
> fix:  revert customer module flag removal

- src/screens/HyperSwitch/Order/OrderEntity.res
- src/utils/LogicUtils.res
> fix: Business & Shipping Details Updated

- src/screens/HyperSwitch/SDKPayment/SDKPaymentTypes.res
- src/screens/HyperSwitch/SDKPayment/SDKPaymentUtils.res
> feat: zero payment added

- src/screens/HyperSwitch/SDKPayment/SDKPaymentUtils.res
> fix: curruncy fix

- src/screens/HyperSwitch/SDKPayment/SDKPaymentUtils.res
> fix: currency change

- src/screens/HyperSwitch/Connectors/ConnectorUtils.res
> feat: Cybersource enabled in Prod

- src/screens/HyperSwitch/Surcharge/Surcharge.res
- src/screens/HyperSwitch/Surcharge/SurchargeUtils.res
> fix: make tax_on_surcharge optional and add description

- src/screens/HyperSwitch/SDKPayment/SDKPage.res
- src/screens/HyperSwitch/SDKPayment/SDKPaymentTypes.res
- src/screens/HyperSwitch/SDKPayment/SDKPaymentUtils.res
- src/screens/HyperSwitch/SDKPayment/WebSDK.res
> fix: floating point value fix for test payment

- src/screens/HyperSwitch/UserManagement/InviteUsers.res
> chore: refactor invite users

- src/screens/HyperSwitch/Routing/RoutingUtils.res
- src/screens/HyperSwitch/Routing/VolumeSplitRouting.res
- src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
- src/screens/HyperSwitch/RoutingRevamp/BasicDetailsForm.res
- src/screens/HyperSwitch/Surcharge/Surcharge.res
- src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchAuthUtils.res
> fix: make basic details form to accept form input without Save button

- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/utils/AccessControl.res
> fix: Access Control Issue

- src/hooks/ListHooks.res
- src/screens/HyperSwitch/Analytics/HomePageOverview/HomePageOverviewComponent.res
- src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
- src/screens/HyperSwitch/Connectors/ConnectorList.res
- src/screens/HyperSwitch/Connectors/ConnectorPaymentMethod.res
- src/screens/HyperSwitch/Connectors/ConnectorTableUtils.res
- src/screens/HyperSwitch/Connectors/ConnectorTypes.res
- src/screens/HyperSwitch/Connectors/ConnectorUIUtils/PaymentMethod.res
- src/screens/HyperSwitch/Connectors/ConnectorUtils.res
- src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
- src/screens/HyperSwitch/Home/QuickStart/QuickStartUIUtils.res
- src/screens/HyperSwitch/Home/QuickStart/QuickStartUtils.res
- src/screens/HyperSwitch/Routing/PriorityRouting.res
- src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
- src/screens/HyperSwitch/SetupAccount/HSwitchSetupAccountUtils.res
- src/screens/HyperSwitch/Utils/HSwitchUtils.res
- src/screens/HyperSwitch/Utils/UtilsTypes.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
> chore: utils refactor

- src/hooks/AuthHooks.res
> fix: headers issue

- src/hooks/AuthHooks.res
> fix: content type fix

- src/screens/HyperSwitch/Connectors/ConnectorPreview.res
> fix: close connector drop down bydefault

- .github/workflows/release-stable-version.yml
> chore: Update release-stable-version.yml

- src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
- src/screens/HyperSwitch/Order/OrderUIUtils.res
> fix: UI css fixes

- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchAuthUtils.res
> fix: Switch Merchant Issue

- .github/workflows/cypress-test.yml
- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/entryPoints/hyperswitch/Provider/GlobalProvider.res
- src/entryPoints/hyperswitch/Provider/ProviderTypes.res
- src/entryPoints/hyperswitch/SidebarValues.res
- src/screens/HyperSwitch/Analytics/HomePageOverview/HomePageOverviewComponent.res
- src/screens/HyperSwitch/Home/HomeV2.res
- src/screens/HyperSwitch/Home/ProdIntent/ProdIntentForm.res
- src/screens/HyperSwitch/Home/QuickStart/GoLive.res
- src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/IntegrateYourAppLanding.res
https://github.com/juspay/hyperswitch-control-center/assets/120017870/f7a595f5-e88a-4bdc-bbd3-f75f760549fc
> fix: glitch in homepage

- src/components/Calendar.res
- src/components/CalendarList.res
- src/components/DatePicker.res
- src/components/DateRangePicker.res
- src/components/DynamicChart.res
- src/components/DynamicSingleStat.res
- src/components/InfraCalendar.res
- src/components/InfraCalendarList.res
- src/components/NewCalendar.res
- src/components/NewCalendarList.res
- src/entities/analytics/AnalyticsUtils.res
- src/hooks/DateRefreshHooks.res
- src/hooks/TimeZoneHook.res
- src/libraries/DayJs.res
- src/libraries/RRule.res
- src/screens/HyperSwitch/Analytics/DownloadReportModal.res
- src/screens/HyperSwitch/HSiwtchTimeZoneUtils.res
- src/screens/HyperSwitch/HSwitchRemoteFilter.res
- src/screens/HyperSwitch/PaymentLogs/PaymentLogs.res
- src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/HSwitchAgreementScreen.res
- src/utils/AnalyticsNewUtils.res
- src/utils/DateRangeUtils.res
- src/utils/DateTimeUtils.res
- src/utils/TimeZoneConversion.res
> chore: date core api changes

- src/hooks/AuthHooks.res
> fix: headers object issue

- config/FeatureFlag.json
> chore: Payout Enabled

- src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
> feat: change switch merchant response - filter is_active

- src/screens/HyperSwitch/Order/Orders.res
> fix: payments header button alignment

- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/screens/HyperSwitch/Others/CompanyNameModal.res
- src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/LiveEndpointsSetup.res
- src/screens/HyperSwitch/Settings/HSwitchSettingTypes.res
- src/screens/HyperSwitch/Settings/MerchantAccountUtils.res
- src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
> feat: add company name

- src/entryPoints/hyperswitch/HyperSwitchApp.res
> fix: Permsision API Changes

- src/screens/HyperSwitch/Connectors/ConnectorUtils.res
> feat: enable VOLT in Live

- src/components/priority-logics/AddPLGateway.res
- src/screens/HyperSwitch/Connectors/ConnectorTableUtils.res
- src/screens/HyperSwitch/Order/OrderEntity.res
- src/screens/HyperSwitch/Order/OrderTypes.res
- src/screens/HyperSwitch/Order/ShowOrder.res
- src/screens/HyperSwitch/Recon/Recon.res
- src/screens/HyperSwitch/Routing/AdvancedRouting/RoutingPreviewer.res
- src/screens/HyperSwitch/Routing/DefaultRouting.res
- src/screens/HyperSwitch/RoutingRevamp/AddRuleGateway.res
- src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
1. Removed recon video from recon module 
2. Added payment method details under show payment details 
3. Added profileId-profileLabel in Default routing
> fix: Minor Ui changes

- config/FeatureFlag.json
- src/entryPoints/hyperswitch/AcceptInvite.res
- src/entryPoints/hyperswitch/FeatureFlagUtils.res
- src/entryPoints/hyperswitch/HyperSwitchEntry.res
- src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchAuthUtils.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchEmailVerifyScreen.res
> feat: Feature flag accept invite

- src/components/HyperSwitchLogo.res
- src/screens/HyperSwitch/APIUtils/APIUtils.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
- src/screens/login/HSwitchLoginFlow/HyperSwitchEmailVerifyScreen.res
> fix: reset password local storage issue

- .env
- src/entryPoints/hyperswitch/AcceptInvite.res
> fix: fix accept invite re-render issue

- src/entryPoints/hyperswitch/HyperSwitchApp.res
- src/entryPoints/hyperswitch/HyperswitchAtom.res
- src/screens/HyperSwitch/Others/CompanyNameModal.res
- src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
- src/screens/HyperSwitch/SwitchMerchant/SwitchMerchantListHook.res
- src/screens/HyperSwitch/SwitchMerchant/SwitchMerchantUtils.res
> feat: Switch merchant API Recoil Addition

- src/entryPoints/hyperswitch/SidebarValues.res
> chore: Sidebar Connector Hierarchy changes

- src/screens/Analytics/HomePageOverview/HomePageOverviewComponent.res
- src/screens/Connectors/ConnectPayPalFlow/ConnectPayPal.res
- src/screens/Connectors/ConnectorAccountDetails.res
- src/screens/Connectors/ConnectorAccountDetailsHelper.res
- src/screens/Connectors/ConnectorHome.res
- src/screens/Connectors/ConnectorPaymentMethod.res
- src/screens/Connectors/ConnectorPreview.res
- src/screens/Connectors/ConnectorTableUtils.res
- src/screens/Connectors/ConnectorTypes.res
- src/screens/Connectors/ConnectorUIUtils/IntegrationHelp.res
- src/screens/Connectors/ConnectorUIUtils/PaymentMethod.res
- src/screens/Connectors/ConnectorUtils.res
- src/screens/Connectors/Wallets/Wallet.res
- src/screens/Disputes/DisputesUtils.res
- src/screens/Disputes/ShowDisputes.res
- src/screens/Disputes/UploadEvidenceForDisputes.res
- src/screens/Helpers/HelperComponents.res
- src/screens/Home/CommonConnectorFlow/QuickStartConnectorFlow.res
- src/screens/Home/CommonConnectorFlow/SetupConnector.res
- src/screens/Home/QuickStart/QuickStartUIUtils.res
- src/screens/Home/QuickStart/QuickStartUtils.res
- src/screens/Processors/ProcessorCards.res
- src/screens/SelfServe/HSwitchProdOnboarding/ChooseConnector.res
- src/screens/SelfServe/HSwitchProdOnboarding/ProdOnboardingLanding.res
- src/screens/SelfServe/HSwitchProdOnboarding/ProdOnboardingUIUtils.res
- src/screens/SelfServe/HSwitchProdOnboarding/ProdOnboardingUtils.res
- src/screens/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
- src/screens/StripePlusPaypal/StripePlusPaypal.res
- src/screens/StripePlusPaypal/StripePlusPaypalUIUtils.res
> Refactor: Added connector types and renamed the connector util functions

- src/screens/APIUtils/APIUtils.res
- src/screens/Hooks/ClearRecoilValueHook.res
> fix: clear recoil state on logout

- src/Recoils/HyperswitchAtom.res
- src/Recoils/TableAtoms.res
- src/screens/Customers/Customers.res
- src/screens/Customers/CustomersEntity.res
- src/screens/Developer/APIKeys/DeveloperUtils.res
- src/screens/Developer/APIKeys/KeyManagement.res
- src/screens/Disputes/Disputes.res
- src/screens/Disputes/DisputesEntity.res
- src/screens/Hooks/ClearRecoilValueHook.res
- src/screens/Order/OrderEntity.res
- src/screens/Order/Orders.res
- src/screens/Refunds/Refund.res
- src/screens/Refunds/RefundEntity.res
- src/screens/Routing/HistoryEntity.res
- src/screens/Routing/RoutingStack.res
- src/screens/Routing/RoutingUtils.res
- src/screens/Routing/VolumeSplitRouting.res
- src/screens/RoutingRevamp/AdvancedRouting.res
> refactor: moved all the atoms to one folder

- src/screens/SelfServe/HSwitchProdOnboarding/LiveEndpointsSetup.res
> fix: live onboarding webhook url update fix

- CHANGELOG.md
- src/Recoils/HyperswitchAtom.res
- src/screens/Connectors/ConnectorAccountDetailsHelper.res
- src/screens/Connectors/ConnectorPreview.res
- src/screens/Developer/PaymentSettings/PaymentSettings.res
- src/screens/Developer/PaymentSettings/PaymentSettingsList.res
- src/screens/Developer/PaymentSettings/PaymentSettingsListEntity.res
- src/screens/Hooks/ClearRecoilValueHook.res
- src/screens/Routing/DefaultRouting.res
- src/screens/RoutingRevamp/BasicDetailsForm.res
- src/screens/SDKPayment/SDKPage.res
- src/screens/SelfServe/HSwitchProdOnboarding/LiveEndpointsSetup.res
- src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
- src/screens/Settings/BusinessMapping/BusinessProfile.res
- src/screens/Settings/MerchantAccountUtils.res
- src/utils/Mappers/BusinessProfileMapper.res
> refactor: Business recoil value from string to typed

- src/screens/Connectors/ConnectorUIUtils/PaymentMethod.res
> fix: cursor changes for clickable label

- src/screens/UserManagement/UserManagementUtils.res
- src/screens/UserManagement/UserRoleEntity.res
Backend is now sending `role_names` in `snake_case` in list roles api. This PR converts them to Title Case before rendering them.
Also added missing roles.
closes #466
> fix: Add a mapper to change role names from `snake_case` to `Title Case`

- src/screens/Home/HomeV2.res
- src/screens/SwitchMerchant/SwitchMerchant.res
> style: home page ui

- src/screens/Connectors/ConnectorUtils.res
- src/screens/Home/QuickStart/QuickStartUIUtils.res
- src/screens/Home/QuickStart/QuickStartUtils.res
- src/screens/Processors/ProcessorCards.res
> fix: Quick start connector selection bug and connector list bug fixes

- src/entryPoints/Provider/ProviderHelper.res
- src/screens/UserManagement/CreateCustomRole.res
- src/screens/UserManagement/InviteUsers.res
- src/screens/UserManagement/ShowUserData.res
- src/screens/UserManagement/UserManagementTypes.res
- src/screens/UserManagement/UserManagementUtils.res
> refactor: Removed permissions 

- src/entryPoints/HyperSwitchApp.res
- src/entryPoints/SidebarValues.res
- src/screens/Connectors/ConnectorList.res
- src/screens/Connectors/ConnectorTypes.res
- src/screens/Connectors/ConnectorUtils.res
- src/screens/Developer/APIKeys/DeveloperUtils.res
- src/screens/Developer/PaymentSettings/PaymentSettings.res
- src/screens/FraudAndRisk/FRMPaymentMethods.res
- src/screens/FraudAndRisk/FRMTypes.res
- src/screens/FraudAndRisk/FRMUtils.res
- src/screens/Home/ProdIntent/ProdVerifyModal.res
- src/screens/Home/ProdIntent/ProdVerifyModalUtils.res
- src/screens/Home/QuickStart/GoLive.res
- src/screens/ThreeDsProcessors/ThreeDsConnectorList.res
- src/screens/ThreeDsProcessors/ThreeDsProcessorHome.res
1. Prod onboarding form changes 
2. Switch Merchant dropdown changes
> fix: prod onboarding form and switch merchant dropdown changes

- config/FeatureFlag.json
- src/entryPoints/FeatureFlagUtils.res
- src/entryPoints/HyperSwitchApp.res
- src/entryPoints/SidebarValues.res
> chore: added feature flag for 3DS authenticator

- src/entryPoints/HyperSwitchApp.res
- src/entryPoints/SidebarValues.res
- src/screens/ThreeDsProcessors/ThreeDsConnectorList.res
- src/screens/ThreeDsProcessors/ThreeDsProcessorHome.res
> fix: 3ds-url-fix

- src/screens/SelfServe/HSwitchProdOnboarding/ChooseConnector.res
- src/screens/SelfServe/HSwitchProdOnboarding/ProdOnboardingLanding.res
> fix: prod onboarding screen fix

- src/screens/Connectors/ConnectorUtils.res
- src/screens/Disputes/ShowDisputes.res
- src/screens/Home/QuickStart/QuickStartUIUtils.res
- src/screens/Home/QuickStart/QuickStartUtils.res
> fix: disputes show counter button condition change

- src/screens/Connectors/ConnectorAccountDetails.res
- src/screens/Connectors/ConnectorPaymentMethod.res
- src/screens/Connectors/ConnectorPreview.res
- src/screens/FraudAndRisk/FRMSummary.res
- src/screens/Processors/ProcessorCards.res
> chore: added mixpanel events for connector flow

- src/screens/Disputes/ShowDisputes.res
- src/screens/Disputes/UploadEvidenceForDisputes.res
> fix: Upload evidence modal fix

- src/components/MakeRuleFieldComponent.res
- src/screens/RoutingRevamp/AddRuleGateway.res
- src/screens/RoutingRevamp/AdvancedRouting.res
- src/screens/RoutingRevamp/Previewers/RulePreviewer.res
> fix: rule based routing on click of ruleno warning fix

- src/screens/Analytics/Logs/DisputeLogs/DisputeLogs.res
- src/screens/Analytics/Logs/LogUtils/LogUtils.res
- src/screens/Analytics/Logs/PaymentLogs/PaymentLogs.res
- src/screens/Analytics/Logs/RefundLogs/RefundLogs.res
- src/screens/Disputes/ShowDisputes.res
- src/screens/Order/ShowOrder.res
- src/screens/Refunds/ShowRefund.res
> chore: enabled audit log for all connectors

- src/components/RemoteFiltersUtils.res
- src/context/DataTableFilterOpenContext.res
- src/context/DatatableContext.res
- src/context/FilterContext.res
- src/entryPoints/Provider/ProviderHelper.res
- src/entryPoints/Provider/ProviderTypes.res
- src/screens/Connectors/ConnectorPreview.res
- src/screens/Home/HomeUtils.res
- src/screens/Order/OrderTypes.res
- src/screens/Routing/VolumeSplitRouting.res
- src/screens/ThreeDSFlow/HSwitchThreeDS.res
- src/screens/UserManagement/CreateCustomRole.res
- src/screens/UserManagement/RolesEntity.res
> chore: core changes

- cypress/e2e/quick-start/sbx-quick-start.cy.js
- src/components/Button.res
- src/components/Button.resi
- src/components/form/FormRenderer.res
> chore: custom testId for buttons

- src/screens/Disputes/ShowDisputes.res
> fix: days to respond in show disputes issue

- config/FeatureFlag.json
- src/entryPoints/FeatureFlagUtils.res
- src/entryPoints/HyperSwitchApp.res
- src/entryPoints/SidebarValues.res
> chore: added feature flag for disputes

- config/FeatureFlag.json
- src/entryPoints/FeatureFlagUtils.res
- src/entryPoints/HyperSwitchApp.res
- src/entryPoints/SidebarValues.res
- src/screens/ConfigurePMTs/PaymentMethodConfig.res
- tailwind.config.js
> fix: configure pmts page issue fix

- src/screens/Connectors/ConnectorPreview.res
- src/screens/Developer/PaymentSettings/PaymentSettings.res
- src/screens/Settings/BusinessDetails.res
- src/screens/Settings/MerchantAccountUtils.res
> fix: return url and webhook url regex change

- src/components/InputFields.res
- src/components/InputFields.resi
> chore: checkbox input type added

- src/screens/Settings/MerchantAccountUtils.res
> fix: webhook url and return url regex change

- src/screens/Analytics/Logs/LogUtils/ApiDetailsComponent.res
- src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
- src/screens/Analytics/Logs/LogUtils/LogUtils.res
> chore: audit log ui fixes

- src/components/Button.res
- src/config/UIConfig.res
> fix: Ui button css changes

- src/utils/HSwitchGlobalVars.res
> fix: agreement version change

- src/screens/Order/OrderEntity.res
> fix: base url show payments fix

- src/screens/Connectors/ConnectorUtils.res
> feat: Authorize.net in prod

- src/screens/Connectors/ConnectorAccountDetailsHelper.res
> fix: empty box in connector fix

- src/entryPoints/HyperSwitchApp.res
> fix: onboarding survey api call fix

- config/config.toml
- src/components/DynamicFilter.res
- src/screens/HSwitchRemoteFilter.res
- src/screens/Order/OrderUIUtils.res
- src/screens/Order/Orders.res
> fix: filter fix

- CHANGELOG.md
- cypress.config.js
- cypress/e2e/auth/auth.cy.js
- cypress/e2e/processors/processores-paypal_test.cy.js
- cypress/e2e/quick-start/prod-quick-start.cy.js
- cypress/e2e/quick-start/sbx-quick-start.cy.js
- src/screens/Analytics/DisputeAnalytics/DisputeAnalytics.res
- src/screens/Analytics/DisputeAnalytics/DisputeAnalyticsEntity.res
- src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
- src/screens/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
- src/screens/Analytics/RefundsAnalytics/RefundsAnalytics.res
- src/screens/Analytics/RefundsAnalytics/RefundsAnalyticsEntity.res
- src/screens/Home/ProdIntent/ProdVerifyModal.res
- src/screens/Others/OnboardingSurveyModalUtils.res
- src/utils/HSwitchGlobalVars.res
> fix: updated calendly link

- src/screens/Home/Home.res
- src/screens/Home/HomeV2.res
> fix: accept invite in home fix

- src/screens/Connectors/ConnectorUtils.res
> feat: Bambora to prod

- config/config.toml
- src/components/CustomCharts/LineChartUtils.res
- src/components/DynamicChart.res
- src/components/DynamicTabs.res
- src/components/SelectModal.res
- src/screens/Analytics/Analytics.res
- src/screens/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
- src/screens/Analytics/RefundsAnalytics/RefundsAnalyticsEntity.res
> chore: analytics modification

- src/entryPoints/AuthModule/TotpAuth/TotpSetup.res
- src/entryPoints/HyperSwitchApp.res
- src/screens/Others/SbxOnboardingSurvey.res
- src/screens/SwitchMerchant/SwitchMerchant.res
> fix: totp switch merchant bug fix

- src/entryPoints/AuthModule/TotpAuth/TotpSetup.res
> fix: TOTP setup access-code changes

- src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
https://github.com/juspay/hyperswitch-control-center/assets/120017870/23837b7b-237f-4efc-9989-c88cdbb3613f
Prevent the Default browser events when you press cmd + K
> fix: global search not working in Firefox

- src/entryPoints/HyperSwitchEntry.res
- src/entryPoints/configs/HyperSwitchConfigTypes.res
Add Default favicon when favicon value is empty
> fix: favicon missing in firebox

- src/screens/Customers/ShowCustomers.res
- src/screens/UserManagement/CreateCustomRole.res
Click on the text of the Custom role should make enable also the checkbox.
> fix: checkbox click & text click select custom role

- src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
> fix: input box issue fix

- src/screens/Analytics/AnalyticsTypes.res
- src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalyticsEntity.res
- src/screens/Order/OrderEntity.res
- src/screens/Order/OrderTypes.res
- src/screens/Order/ShowOrder.res
Added **External Authentication Details** block in payments
closes #565
> feat: added authentication details block in payment details

- src/components/DynamicChart.res
- src/screens/Analytics/Analytics.res
> fix: user analytics fix

- src/screens/Analytics/AnalyticsTypes.res
- src/screens/Analytics/GlobalSearchResults/Tables/PaymentAttempt/PaymentAttemptEntity.res
- src/screens/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
- src/screens/Order/OrderEntity.res
- src/screens/Order/OrderTypes.res
added client cols in payment analytics and payment attempt entity
closes #565
> feat: added client cols in payment analytics and payment attempt entity

- src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalyticsEntity.res
Added disabled metrics (to fetch metrics before transforming the data)
closes #565
> fix: authentication analytics funnel

- src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
> chore: profile page component addition for 2fa

- src/entryPoints/HyperSwitchEntry.res
> chore: page title changes

- src/screens/Home/ProdIntent/ProdVerifyModalUtils.res
> fix: Production access form fields addition

- src/screens/Connectors/ConnectorHome.res
- src/screens/Connectors/ConnectorUtils.res
Dummy connector screen warning added.
> fix: dummy connector warnings

- src/screens/SDKPayment/SDKPaymentUtils.res
> fix: amount to capture

- src/entryPoints/AuthModule/Common/CommonAuthTypes.res
- src/entryPoints/AuthModule/Common/CommonAuthUtils.res
- src/entryPoints/AuthModule/TotpAuth/TotpRecoveryCodes.res
- src/entryPoints/AuthModule/TotpAuth/TotpSetup.res
> fix: totp phase2 bugfixes

- src/screens/SDKPayment/SDKPage.res
> fix: disable sdk show preview

- src/screens/Order/Orders.res
- src/screens/Refunds/Refund.res
> fix: refunds filters url fix

- src/entryPoints/AuthModule/TotpAuth/TotpRecoveryCodes.res
- src/entryPoints/AuthModule/TotpAuth/TotpUtils.res
- src/screens/Settings/HSwitchProfile/ModifyTwoFaSettings.res
> feat: regenerate recovery codes

- src/entryPoints/AcceptInviteHome.res
- src/entryPoints/AuthModule/TotpAuth/TotpSetup.res
- src/entryPoints/AuthModule/TotpAuth/TotpTypes.res
- src/entryPoints/AuthModule/TotpAuth/TotpUtils.res
- src/entryPoints/AuthModule/TotpAuth/TwoFaElements.res
- src/screens/Home/Home.res
- src/screens/Home/HomeUtils.res
- src/screens/Home/HomeV2.res
- src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
> fix: totp bug fixes with accept invite in home

- src/screens/Refunds/RefundUtils.res
> chore: fix refund filters

- src/screens/Connectors/ConnectorUtils.res
> fix: Removed required fields for metadata cybersource

- CHANGELOG.md
- src/entryPoints/AuthModule/TotpAuth/TotpAuthScreen.res
- src/entryPoints/AuthModule/TotpAuth/TotpAuthWrapper.res
- src/entryPoints/AuthModule/TotpAuth/TotpSetup.res
- src/screens/Settings/HSwitchProfile/ModifyTwoFaSettings.res
> refactor: auth header as a separate component

- src/screens/Order/OrderEntity.res
> fix: payments table description column fix

- src/screens/SwitchMerchant/SwitchMerchant.res
> fix: switch merchant dialog box ui issue

- src/screens/SwitchMerchant/SwitchMerchant.res
> chore: switch merchant quick fix

- src/entryPoints/AuthModule/AuthUtils.res
- src/entryPoints/AuthModule/AuthWrapper.res
- src/entryPoints/AuthModule/PreLoginModule/AcceptInviteScreen.res
- src/entryPoints/AuthModule/PreLoginModule/DecisionScreen.res
- src/entryPoints/AuthModule/PreLoginModule/MerchantSelectScreen.res
- src/entryPoints/AuthModule/PreLoginModule/PreLoginTypes.res
- src/entryPoints/AuthModule/PreLoginModule/PreLoginUtils.res
- src/entryPoints/AuthModule/PreLoginModule/VerifyUserFromEmail.res
- src/entryPoints/AuthModule/SSOAuth/SSODecisionScreen.res
- src/entryPoints/AuthModule/SSOAuth/SSOTypes.res
- src/entryPoints/AuthModule/SSOAuth/SSOUtils.res
- src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaUtils.res
> chore: sso decision screen addition

- src/screens/Connectors/Wallets/ApplePayWalletIntegration.res
- src/screens/Connectors/Wallets/ApplePayWalletIntegrationUtils.res
> chore: map the display name to label

- src/context/AuthInfoProvider.res
- src/entryPoints/AcceptInvite.res
- src/entryPoints/AuthModule/AuthUtils.res
- src/entryPoints/AuthModule/AuthWrapper.res
- src/entryPoints/AuthModule/SSOAuth/SSODecisionScreen.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaUtils.res
- src/entryPoints/AuthModule/UserInfoScreen.res
- src/screens/HSLocalStorage.res
> refactor: local storage key name change

- src/screens/Disputes/UploadEvidenceForDisputes.res
> fix: disputes accept dispute button condition change

- src/components/Filter.res
> chore: filters ui in newline

- src/screens/Connectors/ConnectorUtils.res
> chore: add zsl in prod

- src/context/AuthInfoProvider.res
- src/entryPoints/AuthModule/AuthUtils.res
- src/entryPoints/AuthModule/AuthWrapper.res
- src/entryPoints/AuthModule/BasicAuth/BasicAuth.res
- src/entryPoints/AuthModule/BasicAuth/BasicAuthScreen.res
- src/entryPoints/AuthModule/BasicAuth/BasicEmailVerifyScreen.res
- src/entryPoints/AuthModule/Common/CommonAuth.res
- src/entryPoints/AuthModule/Common/CommonAuthHooks.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuthScreen.res
- src/hooks/AuthHooks.res
- src/screens/APIUtils/APIUtils.res
- src/screens/Home/DelayedVerificationBanner.res
- src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
- src/screens/UserManagement/InviteUsers.res
- src/screens/UserManagement/ShowUserData.res
> Fix: url changes to include auth_id

- CHANGELOG.md
- config/config.toml
- src/context/AuthInfoProvider.res
- src/context/FilterContext.res
- src/entryPoints/AcceptInvite.res
- src/entryPoints/AuthModule/AuthModuleHooks.res
- src/entryPoints/AuthModule/AuthProviderTypes.res
- src/entryPoints/AuthModule/AuthUtils.res
- src/entryPoints/AuthModule/AuthWrapper.res
- src/entryPoints/AuthModule/Common/CommonAuthHooks.res
- src/entryPoints/AuthModule/Common/CommonAuthTypes.res
- src/entryPoints/AuthModule/PreLoginModule/AcceptInviteScreen.res
- src/entryPoints/AuthModule/PreLoginModule/AuthSelect.res
- src/entryPoints/AuthModule/PreLoginModule/DecisionScreen.res
- src/entryPoints/AuthModule/PreLoginModule/PreLoginTypes.res
- src/entryPoints/AuthModule/PreLoginModule/PreLoginUtils.res
- src/entryPoints/AuthModule/SSOAuth/SSODecisionScreen.res
- src/entryPoints/AuthModule/SSOAuth/SSOTypes.res
- src/entryPoints/AuthModule/SSOAuth/SSOUtils.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaUtils.res
- src/entryPoints/AuthModule/UserInfoScreen.res
- src/entryPoints/HyperSwitchEntry.res
- src/entryPoints/HyperSwitchEntryUtils.res
- src/hooks/AuthHooks.res
- src/libraries/SessionStorage.res
- src/screens/APIUtils/APIUtils.res
- src/screens/APIUtils/APIUtilsTypes.res
- src/screens/HSLocalStorage.res
> feat: SSO integration in dashboard

- src/screens/Connectors/Wallets/ApplePayWalletIntegration.res
- src/screens/Connectors/Wallets/ApplePayWalletIntegrationUtils.res
> chore: Add field domain name as optional field

- src/context/AuthInfoProvider.res
- src/entryPoints/AcceptInvite.res
- src/entryPoints/AuthModule/AuthWrapper.res
- src/entryPoints/AuthModule/BasicAuth/BasicAuthWrapper.res
- src/entryPoints/AuthModule/BasicAuth/BasicDecisionScreen.res
- src/entryPoints/AuthModule/BasicAuth/BasicEmailVerifyScreen.res
- src/entryPoints/AuthModule/BasicAuth/BasicInviteFromEmail.res
- src/entryPoints/AuthModule/Common/CommonInviteScreen.res
- src/entryPoints/AuthModule/PreLoginModule/AcceptInviteScreen.res
- src/entryPoints/AuthModule/PreLoginModule/AuthSelect.res
- src/entryPoints/AuthModule/PreLoginModule/DecisionScreen.res
- src/entryPoints/AuthModule/PreLoginModule/MerchantSelectScreen.res
- src/entryPoints/AuthModule/PreLoginModule/ResetPassword.res
- src/entryPoints/AuthModule/PreLoginModule/VerifyUserFromEmail.res
- src/entryPoints/AuthModule/SSOAuth/SSODecisionScreen.res
- src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
- src/entryPoints/AuthModule/UserInfoScreen.res
- src/libraries/CookieStorage.res
- src/screens/APIUtils/APIUtils.res
- src/screens/Home/HomeUtils.res
- src/screens/PostLoginScreen/PostLoginScreen.res
- src/screens/Sidebar/Sidebar.res
- src/screens/Utils/DefaultLandingPage.res
> refactor: handle logout hook changes

- src/context/AuthInfoProvider.res
- src/entryPoints/AuthModule/AuthWrapper.res
- src/entryPoints/AuthModule/BasicAuth/BasicDecisionScreen.res
- src/entryPoints/AuthModule/BasicAuth/BasicEmailVerifyScreen.res
- src/entryPoints/AuthModule/BasicAuth/BasicInviteFromEmail.res
- src/entryPoints/AuthModule/Common/CommonInviteScreen.res
- src/entryPoints/AuthModule/PreLoginModule/AcceptInviteScreen.res
- src/entryPoints/AuthModule/PreLoginModule/AuthSelect.res
- src/entryPoints/AuthModule/PreLoginModule/DecisionScreen.res
- src/entryPoints/AuthModule/PreLoginModule/MerchantSelectScreen.res
- src/entryPoints/AuthModule/PreLoginModule/ResetPassword.res
- src/entryPoints/AuthModule/PreLoginModule/VerifyUserFromEmail.res
- src/entryPoints/AuthModule/SSOAuth/SSODecisionScreen.res
- src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
- src/entryPoints/AuthModule/UserInfoScreen.res
> chore: singout api call falling using spt

- src/components/DynamicTabs.res
- src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
> chore: payment logs ui changes

- src/entryPoints/AuthModule/AuthModuleHooks.res
- src/entryPoints/AuthModule/AuthWrapper.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuthScreen.res
> fix: signup auth methods

- src/screens/Routing/RoutingStack.res
- fixed useMemo dependency in Routing page
> fix: routing stack bug fix

- config/config.toml
- src/components/CustomCharts/LineChartUtils.res
- src/components/DynamicChart.res
- src/components/DynamicSingleStat.res
> feat: analytics more granularity to the graphs 

- src/screens/Order/OrderEntity.res
- src/screens/Order/OrderTypes.res
- src/screens/Order/ShowOrder.res
> chore: added merchant order reference id field in "more payment details"

- src/screens/Order/OrderEntity.res
> fix: heading for new table column merchant ref id

- src/entryPoints/SidebarValues.res
- src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
> fix: Recon not showing fixes

- src/components/Paginator.res
- src/screens/APIUtils/APIUtils.res
- src/screens/Order/Orders.res
- src/screens/Refunds/Refund.res
> chore: orders and refunds more table items

- src/components/DynamicChart.res
- src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalyticsEntity.res
> fix: user analytics granularity fix

- src/entryPoints/SidebarValues.res
> chore: removed console logs for testing

- src/components/DynamicSingleStat.res
- src/components/Filter.res
- src/components/HSwitchSingleStatWidget.res
- src/screens/Analytics/HomePageOverview/PaymentsOverview/PaymentOverview.res
- src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
- src/screens/Analytics/PaymentsAnalytics/SmartRetryAnalytics.res
- src/screens/Home/HomeUtils.res
> fix: dynamic charts and filter ui fix

- src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
> fix: audit trail  empty log details on load

- src/screens/RoutingRevamp/AdvancedRouting.res
- src/screens/ThreeDSFlow/HSwitchThreeDS.res
Rule based configuration
3ds routing configuration
> chore: inform users about currency denomination in rule based routing

- src/screens/Order/OrderEntity.res
- src/screens/Order/OrderTypes.res
> fix: added attempts count column in payment list table

- src/screens/PayoutRouting/PayoutRoutingStack.res
> fix: payout routing rule list

- src/screens/Connectors/ConnectorUtils.res
- added mifinity payment connector in Prod connector list
> feat: add mifinity to prod

- src/screens/Connectors/ConnectorUtils.res
> chore: enable mifinity prod

- src/screens/Developer/PaymentSettings/PaymentSettings.res
> fix: Add icon fix for safari

- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTable.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptEntity.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptTable.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentEntity.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentTable.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTable.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTableEntity.res
> fix: global search empty table fix

- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/ResultsTableUtils.res
- src/screens/Disputes/ShowDisputes.res
- src/screens/Order/ShowOrder.res
- src/screens/Refunds/ShowRefund.res
Global serach table fetching though customer email fix and payment to payment or refunds to refunds redirecting fix
> fix: global search minor bugs

- src/components/FilterSelectBox.res
- src/components/SelectBox.res
- src/components/SelectBox.resi
- src/components/Table.resi
- src/components/TableUtils.res
- src/components/TableUtils.resi
- src/components/form/PasswordStrengthInputAsChips.res
- src/entryPoints/AuthModule/Common/CommonAuthUtils.res
- src/entryPoints/AuthModule/TwoFaAuth/OtpInput.res
- src/screens/Connectors/ConnectorUtils.res
- src/screens/Developer/APIKeys/DeveloperUtils.res
- src/screens/HSwitchUtils.res
- src/screens/Home/ProdIntent/ProdVerifyModalUtils.res
- src/screens/Order/OrderUIUtils.res
- src/screens/Routing/RoutingUtils.res
- src/screens/Settings/BusinessMapping/BusinessMappingUtils.res
- src/screens/Settings/MerchantAccountUtils.res
- src/utils/LogicUtils.res
Reference: https://rescript-lang.org/docs/manual/latest/api/core/regexp#value-unicode
> chore: core api changes for regex

- src/screens/Connectors/ConnectorPreview.res
> fix: redirect url from payout connector enable/disable

- src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
> fix: global search back button fix

- src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayIntegrationHelper.res
- src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
make customElement as optional
> fix: SimplifiedHelper optional

- src/screens/Order/OrderEntity.res
- src/screens/Order/OrderRefundForm.res
- src/screens/Order/OrderTypes.res
> fix: order customer email fix

- src/screens/SDKPayment/SDKPaymentTypes.res
- src/screens/SDKPayment/SDKPaymentUtils.res
> chore: added frm_metadata in payments api sdk

- src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalyticsEntity.res
Rename single stat titles and tooltip texts for clarity
> fix: rename single stat titles and tooltip texts

- src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalyticsEntity.res
> fix: frictionless success metric fix

- src/screens/Connectors/ConnectorTableUtils.res
added merchant connector id in configured connector table
Requirement
Tested on local, able to see the mca id column in table
> chore: added merchant connector id

- src/screens/FraudAndRisk/FRMInfo.res
backend is not expecting the field additional_merchant_data in api payload, so had to remove that
API was failing, after this change it works
API payload is correct now, no error from backend, getting expected api response after this change
> fix: frm api payload update

- src/screens/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
- src/screens/ThreeDsProcessors/ThreeDsTableEntity.res
added mca id in 3ds and pm auth table
to maintain consistency
column appearing in local testing
> chore: added mca id in 3ds and pm auth table

- src/screens/Connectors/ConnectorMetaData/BankDebit/BankDebit.res
- src/screens/PMAuthenticationProcessor/PMAuthenticationHome.res
a small css change was required in the PM Auth Processor UI
ui bug fix
- Tested locally
- UI bug fixed
> fix: bug fix

- src/screens/Connectors/ConnectorUIUtils/PaymentMethod.res
do not show pm auth sidebar when pm auth is disabled 
bugfix
local testing is working fine
> fix: Feature flag sidebar

- src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRateUtils.res
fixed failure rate formula 
the failure rate shown in the graph should match to 
`  let rate = failureCount /. count *. 100.0`
this equation
> fix: failure rate formula fix

- src/screens/Order/OrderEntity.res
- src/screens/Order/OrderTypes.res
- src/screens/Order/Orders.res
- src/screens/Order/ShowOrder.res
Removed dependency of connector list API on orders page . 
Cannot be tested as this is a chore change
> chore: connector api dependency on orders removed

- src/components/DynamicTabs.res
- src/entryPoints/AuthModule/AuthWrapper.res
bug fi, component not re-rendering on dependency change
to fix the bug
local testing giving expected results
> chore: bug fix audit trail

- src/components/Paginator.res
- src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRateUtils.res
- src/screens/Analytics/PerformanceMonitor/GaugeChart/GaugeChartPerformanceUtils.res
rate gauge label and decimal set to 2 digits 
no of items dropdown fix
> fix: performance monitor bugs

- src/entryPoints/SidebarValues.res
- src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformanceUtils.res
- src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformanceUtils.res
updated the color codes of the performance monitor graphs, legends width fix and spell correction 
The graph legends should take dynamic width so it should not be cropped, spell correction on side bar
> chore: graphs color code update

- src/screens/Payouts/PayoutsList.res
- src/screens/Payouts/PayoutsUtils.res
added the pagination support for payouts table 
change the page numbers and the table should load curesponding offset data
> feat: pagination support for payouts table

- src/entryPoints/AuthModule/Common/CommonAuthHooks.res
- src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
- src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
- src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
- src/screens/Home/Home.res
- src/screens/Home/HomeV2.res
- src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
- src/screens/SwitchMerchant/SwitchMerchant.res
Previously, the user-info API was called only by the provider. However, with the user-management revamp, we may need to call the user-info API explicitly in different places to retrieve updated values.
Cannot change as it is a chore change
> chore: user info provider changes

- src/entryPoints/AuthModule/Common/CommonAuthForm.res
https://github.com/juspay/hyperswitch-control-center/issues/899
only the hyperlink text should be clickable and not around the space
> fix: hyperlinks fix at login page

- src/Recoils/HyperswitchAtom.res
- src/screens/OMPSwitch/MerchantSwitch.res
- src/screens/OMPSwitch/OMPSwitchHelper.res
- src/screens/OMPSwitch/OMPSwitchTypes.res
- src/screens/OMPSwitch/OMPSwitchUtils.res
- src/screens/OMPSwitch/OrgSwitch.res
- src/screens/OMPSwitch/ProfileSwitch.res
Create an atom for Org, Merchant, and Profile lists to be reused across all places where these lists are needed.
Can't test as this is a chore change
> chore: Org, merch ,profile list atom

- src/container/BusinessProfileContainer.res
- src/container/ConnectorContainer.res
- src/container/MerchantAccountContainer.res
- src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
- src/entryPoints/HyperSwitchApp.res
- src/screens/APIUtils/APIUtils.res
- src/screens/APIUtils/APIUtilsTypes.res
- src/screens/Hooks/SwitchHooks.res
- src/screens/OMPSwitch/MerchantSwitch.res
- src/screens/OMPSwitch/OMPSwitchHelper.res
- src/screens/OMPSwitch/OrgSwitch.res
- src/screens/OMPSwitch/ProfileSwitch.res
- src/screens/Sidebar/SidebarSwitch.res
- Some minor UI css changes 
- When the organization, merchant, or profile is changed, the switch will be triggered, and the related components will re-render.
Cannot test as it is a chore change
> chore: switch org , merchant , profile implementation

- src/container/MerchantAccountContainer.res
- src/entryPoints/HyperSwitchApp.res
Closes #1272 
Enable the reconciliation (recon) feature through a feature flag and have two merchants, with recon enabled for one of them. For the merchant with recon enabled, the sidebar should display Recon and Settlement along with their sub-modules. For the merchant without recon enabled, an option to email support to enable recon will be shown.
> fix: recon issue fixed

- src/screens/Connectors/ConnectorUtils.res
connector config
`{
"connector_auth": {
"SignatureKey": {
"api_key": "Key",
"key1": "Merchant ID",
"api_secret": "Shared Secret"
}
},
"credit": [
{
"payment_method_type": "Mastercard"
},
{
"payment_method_type": "Visa"
},
{
"payment_method_type": "Interac"
},
{
"payment_method_type": "AmericanExpress"
},
{
"payment_method_type": "JCB"
},
{
"payment_method_type": "DinersClub"
},
{
"payment_method_type": "Discover"
},
{
"payment_method_type": "CartesBancaires"
},
{
"payment_method_type": "UnionPay"
}
],
"debit": [
{
"payment_method_type": "Mastercard"
},
{
"payment_method_type": "Visa"
},
{
"payment_method_type": "Interac"
},
{
"payment_method_type": "AmericanExpress"
},
{
"payment_method_type": "JCB"
},
{
"payment_method_type": "DinersClub"
},
{
"payment_method_type": "Discover"
},
{ …
> feat: enabled wellsfargo connector

- src/screens/UserManagement/UserRevamp/DropdownWithLoading.res
- src/screens/UserManagement/UserRevamp/InviteMember.res
Fixed organisation , merchant and profile in teams page
For the new user-management-revamp , default organisation , merchant , profile will be by default selected
> fix: fixed all profiles issue in teams

- src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/ResultsTableUtils.res
- src/screens/Analytics/GlobalSearchResults/SearchResultsPage.res
- src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
Merchant id from user-info changes
> fix: merchant id from user-info

- src/screens/OMPSwitch/MerchantSwitch.res
- src/screens/OMPSwitch/OMPSwitchHelper.res
- src/screens/OMPSwitch/ProfileSwitch.res
- src/screens/Sidebar/SidebarSwitch.res
- hover effect on "add new profile" in profile dropdown
- overflow handled for large org and merchant name
fix bugs
ui as expected, refer description
> fix: ui bugs homepage

- src/entryPoints/AuthModule/Common/CommonAuthTypes.res
- src/entryPoints/AuthModule/Common/CommonAuthUtils.res
- src/screens/APIUtils/APIUtils.res
1. Redirecting the user to the homepage is not feasible as it disrupts the user journey. Therefore, whenever we encounter the following (errorcode, subcode) combinations: (400, UR_33) or (404, HE_02), appropriate alternative actions should be taken.
2. In analytics , The merchant payment list is being retrieved for a profile user hence updated the route
1. To replicate the first issue  (In payments) 
- Turn on the user-management-revamp feature flag 
- Have two merchants in which one should have payments 
- click on any payments table and click on any one payment
-  then switch merchant from the sidebar 
- The page should redirect back you to home page rather than showing `payment not found in our records` error page
2. To replicate the first issue  (In connectors)
- Turn on the …
> fix: user management bugs

- src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptEntity.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentEntity.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTableEntity.res
Changes for global search issue
Search for a payment id and when you click on payment details it should not fail and switch to that particular profile
> fix: global search fixes

- src/screens/NewAnalytics/NewAnalyticsHelper.res
- src/screens/NewAnalytics/NewAnalyticsTypes.res
- src/screens/NewAnalytics/OverViewAnalytics/OverViewAnalytics.res
- src/screens/NewAnalytics/OverViewAnalytics/OverViewAnalyticsEntity.res
- src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
- src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
separeted the chat and api enetity for new chart entity module 
enable the new analytics feature flag and the analytics page should work without any UI breaks or erros
> chore: analytics entity refactor

- src/container/ConnectorContainer.res
- src/screens/Connectors/ConnectorUtils.res
> chore: tax processor

- src/screens/Home/HomeUtils.res
Remove  credentials and keys for profile level user in home page
1. Profile level user in sbx 
2. Merchant level user in sbx
3. Profile level user in live
4. Merchant level user in live 
The above cases mentioned in description should pass
> chore: home page changes for profile level users

- src/screens/OMPSwitch/MerchantSwitch.res
Validation added for merchant name : 
1. Alphanumeric in merchant name is allowed 
2. Space is allowed 
3. `_` is allowed 
The above constraints should work
> chore: merchant name validation added

- .github/ISSUE_TEMPLATE/connector_addition.yml
github template for connector addition
to gather sub issues regarding adding connector in dashboard in a single parent issue
open issues in github in this repository
check out the new template
> chore: github template added

- src/screens/OMPSwitch/OMPSwitchHelper.res
- src/screens/UserManagement/UserRevamp/UserManagementHelper.res
- src/screens/UserManagement/UserRevamp/UserManagementLanding.res
> chore: omp views ui changes

- src/screens/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
- src/screens/TaxProcessor/TaxProcessorTableEntity.res
- src/screens/ThreeDsProcessors/ThreeDsTableEntity.res
refer [issue]( https://github.com/juspay/hyperswitch-cloud/issues/6827)
fix bug
working as expected, see attached screenshot
> chore: fix testing bug - displaying Processor in table

- src/components/FilterSelectBox.res
- src/entryPoints/HyperSwitchEntry.res
- src/screens/TransactionViews/TransactionView.res
- src/screens/TransactionViews/TransactionViewUtils.res
bugs resolved in this PR
1. filters and views inconsistent behaviour (views were not getting updated on changing filters)
2. apply button becoming disabled due to incorrectly preserved filters
3. function update required wrt refund entity
4. removed compiler warning
fixing bugs
above mentioned bugs are now resolved
> fix: transaction views

- .github/ISSUE_TEMPLATE/connector_addition.yml
Adding a github issue template for creating new connection integration issues in this repository
gathering all sub-tasks related to connector integration at one place itself 
pls check the screenshot in description
> chore: changes in connector addition template

- src/container/NewAnalyticsContainer.res
- src/screens/NewAnalytics/NewAnalyticsContainerUtils.res
data range filter for new analytics 
enable the new analytics feature flag and u are able to select date range for the analytics page
> feat: new analytics filter

- src/components/UnauthorizedPage.res
removed the url path update to `/unauthorised` in Unauthorised component as it was  directing the dashboard to show Unauthorised screen on every page reload
bugfix
the bug in description is fixed now, 
go to dashboard
go inside any module
reload the page
> fix: error due to unautorised url

- cypress/e2e/connector/connector.cy.js
- src/entryPoints/AuthModule/Common/CommonAuth.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
creation of dummy connector using cypress by following steps provided in the issue
resolves [#6125](https://github.com/juspay/hyperswitch/issues/6125)
> test: creation of dummy connector using cypress

- src/components/CustomizeNotificationsModal.res
- src/components/DynamicTabs.res
- src/components/TableUtils.res
- src/entryPoints/AuthModule/Common/CommonInviteScreen.res
- src/screens/Connectors/ConnectorUIUtils/PaymentMethod.res
- src/screens/Connectors/ConnectorUtils.res
Code standards correction
Code compile basic sanity will work.
> refactor: code changes

- cypress/e2e/connector/connector.cy.js
- src/entryPoints/AuthModule/Common/CommonAuth.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
- ran command npx prettier --write .
- to format the files
refactor
cannot be tested
> chore: ran prettier command to format unformatted file

- src/components/SelectBox.res
The selected item or the active item in the profile and merchant dropdown list now appears on the top. 
This allows better accessibility and good user experience.
Working as described in the description.
> fix: Selected item displays on top of list

- src/screens/Connectors/ConnectorMetaData/GooglePay/GooglePayUtils.res
Added fiuu google pay gateway name:
processor : fiuu
gateway : "molpay"
Requirement
Added and checked the gateway name addition.
> feat: fiuu google pay gateway name

- src/screens/NewAnalytics/NewAnalyticsTypes.res
- src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
overvew section the made the gap between the tiles as 24px as in design and metrics name changes from `payment_processed_amount` to `sessionized_payment_processed_amount` and `payment_count` to `sessionized_payment_processed_count` and the url is changed to V2
the new metrics should return the values correctly that is payment proccesed amount and paym ent count
> chore: overview section spacing fix and payments metrics changes

- cypress/e2e/connector/connector.cy.js
- src/components/Calendar.res
- src/components/DateRangeField.res
Verification of time range filters in payment operations page using cypress by following steps provided in the issue
resolves [#6129](https://github.com/juspay/hyperswitch/issues/6129)
> test: verification of time range filters in payment operations page using cypress

- cypress/e2e/Payment/00001-PaymentOperationsColumns.cy.js
- cypress/support/commands.js
Adds test cases for various UI elements and functionalities on the "Payment Operations" page. 
Resolves https://github.com/juspay/hyperswitch/issues/6131
The following tests were written and executed:
- Customize Columns Test: Ensures all default columns are displayed and allows selecting/deselecting optional columns.
- Valid Search Test: Tests searching for valid columns and verifies the correct results are displayed.
- Invalid Search Test: Tests for searching invalid or non-existent column names.
> test: Verify Columns in Payment operations page

- src/screens/APIUtils/APIUtils.res
- src/screens/GenerateReports/DownloadReportModal.res
- src/screens/MixpanelHook.res
- src/utils/HyperSwitchUtils.res
update the mixpanel metadata properties with 
API URL
API STATUS CODE
API RESPONSE
x-request-id is not accessible 
check the mixpanel track api or check the mixpanel dashboard
> chore: update mixpanel details

- src/entryPoints/AuthModule/Common/CommonInviteScreen.res
- src/entryPoints/AuthModule/PreLoginModule/ListInvitationScreen.res
- src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaLanding.res
- src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
To make the logout process more efficient , `handleLogout` function is used.
Better efficiency.
Tested locally , working fine as expected.
> fix: handle logout

- src/components/PopUpContainer.res
- src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
- src/entryPoints/AuthModule/TwoFaAuth/TwoFaLanding.res
- src/hooks/AuthHooks.res
- src/screens/Settings/HSwitchProfile/TwoFaSettings/RegenerateRC.res
- src/screens/Settings/HSwitchProfile/TwoFaSettings/ResetTotp.res
Bugfixes for the attached issue in two-fa max attempts restriction 
Local testing
> fix: bug fixes for two-fa restriction

- src/components/SelectBox.res
Addition of profile id search in profile dropdown.
https://github.com/user-attachments/assets/4b571f17-9957-4178-b62b-ff4fdcb32fd9
Better user experience
Local Testing.
> feat: profile id search

- src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
fix for sanky when single payment is present 
even thourgh only one payment or only one node is present the sanky should not break
> chore: sankey single value fix

- src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
added dispute count in new analytics overview section 
overview section should show total dispute count
> feat: dispute count analytics for new analytics overview section

- src/components/SelectBox.res
- src/entryPoints/AuthModule/Common/CommonAuthTypes.res
- src/entryPoints/AuthModule/Common/CommonAuthUtils.res
- src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
- src/screens/Hooks/TotpHooks.res
- src/screens/Settings/HSwitchProfile/TwoFaSettings/ResetTotp.res
- TOTP error messages were not shown .
- Profile dropdown not showing properly in new analytics tabs.
Better User experience
Locally
> fix: totp error toast

- src/components/Filter.res
- src/screens/Disputes/DisputesUtils.res
- src/screens/HSwitchRemoteFilter.res
- src/screens/Order/OrderUIUtils.res
- src/screens/Order/Orders.res
- src/screens/Payouts/PayoutsUtils.res
- src/screens/Refunds/RefundUtils.res
Addition of customer ID filter in payment operations.
Feature request
Local testing.
> feat: customer ID filter

- src/screens/PayoutRouting/PayoutRoutingConfigure.res
- src/screens/Routing/DefaultRouting.res
- src/screens/Routing/RoutingConfigure.res
reverting filtering of routing connector list as backend changes are required to support this change
- try updating connector list ordering in routing > default fallback , api should not fail
> chore: reverting routing filtering connector list changes

- src/screens/Connectors/ConnectorPreview.res
fiuu mandates note part added and its only displayed for fiuu connector 
the note should visible for fiuu connector regarding some key verifcation for mandates
> feat: fiuu connector added note part

- src/screens/SDKPayment/WebSDK.res
> chore: sdk fix pr

- src/components/form/BoolInput.res
- src/container/NewAnalyticsContainer.res
- src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
- src/screens/NewAnalytics/NewAnalyticsHelper.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
design feedback changes 
things changed in this pr
> chore: design feedback changes 

- src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
- src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
… change
sepaerated out the table and graph data display so table will show pure data so won't take graphs modified data
the table should contains all the points even though some points might miss in the graph (raraly happens )
> fix: analytics table data display changes and distribution cols order change 

- src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
- src/screens/Analytics/GlobalSearch/GlobalSearchBarHelper.res
fixed the global search enter listener fix which was affecting other pages
> fix: global search enter listener

- src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
changed the global search filters date range from 1 yesr to 1 week
> fix: changed global search date range fix

- config/config.toml
- src/hooks/AuthHooks.res
This PR will enable frontend to use cookies.
Closes #1809.
With local dashboard with cookies enabled.
> feat(authn): Enable cookies

- src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
- src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
- src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
- src/screens/Hooks/OMPSwitchHooks.res
Exposed a ref to hold the latest values for the user-info
Switching merchant
> chore: added ref for user-info to get updated data

- src/screens/Order/OrderEntity.res
- src/screens/SDKPayment/SDKPage.res
- changes order of columns in payments table 
- made profile id as default column
- sdk show preview is clickable when no payment connector is connected which is a bug 
sdk bug in case no payment connector is connected
on clicking show preview (no payment connector )
after fixx
- payments table order of tables 
- sdk show preview button should be disabled when no payment connector is connected
> chore: minor modification for enhancement and bugfix

- src/screens/OMPSwitch/OMPSwitchHelper.res
- src/screens/OMPSwitch/OrgSwitch.res
- removed copy icon
- added Org in heading
- more width for display omp names
ui changes, refer desc.
> chore: omp remove copy icon

- src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
on key press global search fix
> fix: global search on key press fix 

- src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
- src/screens/Analytics/GlobalSearch/GlobalSearchBarHelper.res
- src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
- src/screens/Analytics/GlobalSearch/GlobalSearchTypes.res
filters list update 
revomed these filters from UI
- authentication_type
- client_source
- client_version
added a filter 
- payment_id
payment id filter should work and card last 4 should retrun results
> chore: global search filters list update

- src/container/NewAnalyticsContainer.res
- src/screens/NewAnalytics/NewAnalyticsUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
- src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
- src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
- src/screens/NewAnalytics/SmartRetryAnalytics/NewSmartRetryAnalyticsEntity.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SuccessfulSmartRetryDistribution/SuccessfulSmartRetryDistribution.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SuccessfulSmartRetryDistribution/SuccessfulSmartRetryDistributionTypes.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SuccessfulSmartRetryDistribution/SuccessfulSmartRetryDistributionUtils.res
smart retry successful distribution
> feat: successful smart retry distribution

- src/container/NewAnalyticsContainer.res
- src/screens/NewAnalytics/SmartRetryAnalytics/NewSmartRetryAnalytics.res
smart retry analytics 
enable smart retry feature flag and the modules will show up under smart retry tab
> feat: smart retry analytics modules

- src/screens/HSwitchRemoteFilter.res
- src/screens/Payouts/PayoutsList.res
- src/screens/Transaction/CommonFilters/AmountFilter/AmountFilterUtils.res
- src/screens/Transaction/Disputes/Disputes.res
- src/screens/Transaction/Order/OrderUIUtils.res
- src/screens/Transaction/Order/Orders.res
- src/screens/Transaction/Refunds/Refund.res
- src/screens/Transaction/Refunds/RefundUtils.res
- src/utils/LogicUtils.res
**Addition of amount filter in refunds:**
**Some UI Improvement in the operations tabs :**
**Before:** 
**After:**
> feat: Refunds amount filter and UI enhancements

- src/components/Calendar.res
- src/screens/NewAnalytics/NewAnalyticsHelper.res
- src/screens/NewAnalytics/NewAnalyticsUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPaymentsUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionHelper.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
> fix: analytics minor changes

- src/screens/NewAnalytics/Graphs/BarGraph/BarGraphTypes.res
- src/screens/NewAnalytics/Graphs/BarGraph/BarGraphUtils.res
- src/screens/NewAnalytics/Graphs/LineGraph/LineGraphTypes.res
- src/screens/NewAnalytics/Graphs/LineGraph/LineGraphUtils.res
- src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphUtils.res
- src/screens/NewAnalytics/NewAnalyticsUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
> chore: new analytics text font and color changes

- src/screens/Connectors/ConnectorList.res
- src/screens/FraudAndRisk/FRMSelect.res
- src/screens/PMAuthenticationProcessor/PMAuthenticationConnectorList.res
- src/screens/TaxProcessor/TaxProcessorList.res
- src/screens/ThreeDsProcessors/ThreeDsConnectorList.res
Added search boxes in 3DS Authentication Manager, Fraud & Risk Management, PM Authenticator Processor, Tax Processor 
Bug fix for search boxes
> fix: Search box issues in "Connectors" pages

- src/screens/Connectors/ConnectorUtils.res
added fiuu connector to prod
able to connect fiuu in live mode on local
> chore: add fiuu to prod

- src/reconScreens/ReconConfiguration/ConnectOrderData/ConnectOrderData.res
- src/reconScreens/ReconConfiguration/ConnectProcessorData/ConnectProcessorData.res
- src/reconScreens/ReconConfiguration/ConnectSettlementData/ConnectSettlementData.res
- src/reconScreens/ReconConfiguration/ScheduleReconReports/ScheduleReconReports.res
- src/screens/Connectors/FraudAndRisk/FRMSelect.res
- src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationConnectorList.res
- src/screens/Connectors/PaymentProcessor/ConnectorList.res
- src/screens/Connectors/PayoutProcessor/PayoutProcessorList.res
- src/screens/Connectors/TaxProcessor/TaxProcessorList.res
- src/screens/Connectors/ThreeDsProcessors/ThreeDsConnectorList.res
Recon configuration setup
No testing required
> chore: setup recon configuration

- src/components/SelectBox.res
Fixed the search results appearing in routing of connectors.
https://github.com/user-attachments/assets/98b8a7be-86b8-4f3c-826d-33f23e113397
> chore: Connector search results fix in routing

- src/screens/Transaction/Order/OrderRefundForm.res
- src/screens/Transaction/Order/ShowOrder.res
Refunds popup redesign.
Before:
After:
Better User experience.
Locally.
> refactor: Refunds popup design

- src/context/ThemeProvider.res
Default background not updated.
Before:
after:
UI
Locally
> fix: background color default config fix

- src/entryPoints/HyperSwitchApp.res
- src/entryPoints/SidebarValues.res
- src/screens/OMPSwitch/OMPSwitchUtils.res
- src/screens/UserManagement/UserRevamp/InviteMember.res
- tenant checks for few cases
- analytics omp view dropdown
- invite user for tenant entity
- locally
- check analytics omp dropdown
- check customer section
- check invite user for tenant admin
> chore: added required tenant user checks

- src/screens/Connectors/PaymentProcessor/ConnectorPreview.res
- src/screens/Connectors/PaymentProcessor/ConnectorPreviewHelper.res
- src/screens/Connectors/PaymentProcessor/ConnectorUpdateAuthCreds.res
- tailwind.config.js
Redesigned API Credentials UI
UI Enhancement
Before
After
> fix: Api creds redesign

- src/screens/Helpers/CardUtils.res
- src/screens/Home/HomeUtils.res
- src/screens/OMPSwitch/OMPSwitchHelper.res
- src/screens/UserManagement/UserRevamp/ListRoles.res
- src/screens/UserManagement/UserRevamp/ListUsers.res
- src/screens/UserManagement/UserRevamp/ManageUserModal.res
- src/screens/UserManagement/UserRevamp/NewUserInvitationForm.res
- src/screens/UserManagement/UserRevamp/UserInfo.res
- src/screens/UserManagement/UserRevamp/UserManagementHelper.res
Made responsive home, user management screens
Home Screen
Before:
After:
Before:
After:
Before:
After:
Before: (No modal)
After:
Before:
After:
Before:
After:
Before:
After: scrollable
Before:
After:
> fix: Made responsive

- src/components/SelectBox.res
- src/screens/UserManagement/UserRevamp/UserManagementHelper.res
Dropdown ellipses text and search style update
https://github.com/juspay/hyperswitch-control-center/issues/2024
Before:
After:
> chore: Dropdown ellipses text

- src/components/ACLDiv.res
- src/components/ACLDiv.resi
- src/screens/OMPSwitch/OMPSwitchHelper.res
Removed add new merchant and add new profile based on the role.
https://github.com/juspay/hyperswitch-control-center/issues/1867
Before:
After:
> fix: Dropdown buttons

- src/container/MerchantAccountContainer.res
- src/screens/Home/HomeUtils.res
- src/screens/SDKPayment/SDKPage.res
Moved unused Connector API call to the SDK Page
https://github.com/juspay/hyperswitch-control-center/issues/2015
Before:
After:
> chore: Moved Connector and Business Profile API call to SDK Page

- src/screens/OMPSwitch/OMPSwitchUtils.res
- currently dropdown options for profile roles come as empty, we will show only the profile itself
check omp view dropdown options for profile user role
> chore: dropdown options for profile

- src/screens/NewAnalytics/NewRefundsAnalytics/FailedRefundsDistribution/FailedRefundsDistribution.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSection.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
- src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
- src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
- src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
- src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
new analytics table data ordering and file refactoring 
the data displyaed in table view should be sorted
> chore: minor file refactor and table data ordering

- src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
- src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
mixpanel events for global seach events to track type of search field been paseed in the payload 
the meta data should contains the query and filters been passed in search api call for global search
> feat: global search mixpanel events

- src/screens/NewAnalytics/NewAnalyticsUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
- src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPayments.res
- src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionTypes.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedTypes.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
- src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedTypes.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
new analytics payment page currrency filters 
then all currency is passed no filter is been passed to BE and it would show as USD* and other if any currency selected the api calls happens by passing thefilter in payload and curresposngin currency value should shown
> feat: new analytics filter payments

- src/screens/Hooks/OMPSwitchHooks.res
> chore: show merchant switch toast

- src/APIUtils/APIUtils.res
this pr will start putting x-request-id on mixpanel alerts, it will help to check grafana logs for mixpanel alerts 
when the mixpanel alert is beign triggered it should log x-request-id as well
> feat: mixpanel x request id on alert events

- src/entryPoints/AuthModule/TwoFaAuth/TotpRecoveryCodes.res
- src/screens/Connectors/PaymentProcessor/ConnectorAccountDetailsHelper.res
- src/screens/Connectors/PaymentProcessor/ConnectorHome.res
- src/screens/Connectors/PaymentProcessor/ConnectorPaymentMethod.res
- src/screens/Connectors/PayoutProcessor/PayoutProcessorHome.res
- src/screens/Connectors/PayoutProcessor/PayoutProcessorPaymentMethod.res
- src/screens/Developer/APIKeys/DeveloperUtils.res
- src/screens/HSwitchUtils.res
- src/screens/Home/HomeUtils.res
- src/screens/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
- src/screens/Settings/BusinessMapping/BusinessProfile.res
- src/screens/Settings/HSwitchProfile/TwoFaSettings/RegenerateRC.res
- create new api key
- check the modal after creating api key
> chore: show info banner for download api key

- src/screens/OMPSwitch/OMPSwitchHelper.res
- disabling deselect option for omp views as that was causing bugs
> fix: disable deselecting item

- src/container/NewAnalyticsContainer.res
- src/screens/NewAnalytics/NewAnalyticsUtils.res
- src/screens/NewAnalytics/NewRefundsAnalytics/FailedRefundsDistribution/FailedRefundsDistribution.res
- src/screens/NewAnalytics/NewRefundsAnalytics/FailureReasonsRefunds/FailureReasonsRefunds.res
- src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalytics.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSection.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSectionTypes.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSectionUtils.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedTypes.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedUtils.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsReasons/RefundsReasons.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
- src/screens/NewAnalytics/NewRefundsAnalytics/SuccessfulRefundsDistribution/SuccessfulRefundsDistribution.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
refunds analytics filters 
on changing the filter value the values in graph should change
> feat: new analytics filter refunds

- src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionHelper.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
currency filter smart retry values fixes 
diff currency selection should display diff values
> fix: currency filter value fixes

- src/screens/ConfigurePMTs/PaymentMethodConfigUtils.res
- src/screens/Connectors/ConnectorTypes.res
- src/screens/Connectors/ConnectorUtils.res
- src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationConnectorList.res
- src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationHome.res
- src/screens/Connectors/PaymentProcessor/ConnectorHome.res
- src/screens/Connectors/PaymentProcessor/ConnectorList.res
- src/screens/Connectors/PaymentProcessor/ConnectorPaymentMethod.res
- src/screens/Connectors/PaymentProcessor/ConnectorPreview.res
- src/screens/Connectors/PaymentProcessor/ConnectorUpdateAuthCreds.res
- src/screens/Connectors/PayoutProcessor/PayoutProcessorHome.res
- src/screens/Connectors/PayoutProcessor/PayoutProcessorList.res
- src/screens/Connectors/TaxProcessor/TaxProcessorHome.res
- src/screens/Connectors/TaxProcessor/TaxProcessorList.res
- src/screens/Connectors/ThreeDsProcessors/ThreeDsConnectorList.res
- src/screens/Connectors/ThreeDsProcessors/ThreeDsProcessorHome.res
- src/screens/Developer/PaymentSettings/PaymentSettings.res
- src/screens/Routing/RoutingUtils.res
- src/utils/Mappers/ConnectorListMapper.res
Refactor connector_type item to object mapper
locally
> refactor: connector_type type added

- src/components/Graphs/BarGraph/BarGraph.res
- src/components/Graphs/BarGraph/BarGraphUtils.res
- src/screens/NewAnalytics/NewRefundsAnalytics/FailedRefundsDistribution/FailedRefundsDistribution.res
- src/screens/NewAnalytics/NewRefundsAnalytics/SuccessfulRefundsDistribution/SuccessfulRefundsDistribution.res
- src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
- src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
- src/screens/NewAnalytics/SmartRetryAnalytics/FailureSmartRetryDistribution/FailureSmartRetryDistribution.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SuccessfulSmartRetryDistribution/SuccessfulSmartRetryDistribution.res
Removed dependency of New analytics in bar graph component.
https://github.com/juspay/hyperswitch-control-center/issues/2080
> chore: Change Bar graph component

- src/components/Graphs/BarGraph/BarGraph.res
- src/components/Graphs/LineGraph/LineGraph.res
- src/components/Graphs/SankyGraph/SankeyGraph.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
Changes in line graph and sankey graph options to use them globally
https://github.com/juspay/hyperswitch-control-center/issues/2088
> refactor: changed linegraph and sankeygraph options

- src/screens/Connectors/ConnectorUtils.res
enabled paybox connector on prod
paybox connector should list down in connector list
> chore: enabled paybox connector on prod

- src/entryPoints/HyperSwitchApp.res
- src/screens/Developer/APIKeys/KeyManagement.res
Gave Merchant View Only access to API Keys in Developers Section
https://github.com/juspay/hyperswitch-control-center/issues/2094
Locally
> fix: Merchant View Only Access to APIKeys

- src/screens/Connectors/FraudAndRisk/FRMIntegrationFields.res
- src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationHome.res
- src/screens/Connectors/PaymentProcessor/ConnectorPaymentMethod.res
- src/screens/Connectors/PayoutProcessor/PayoutProcessorPaymentMethod.res
- src/screens/Connectors/ThreeDsProcessors/ThreeDsProcessorHome.res
Before the connector list api was being called but the list was not updating everytime.
In Payment processors, Payout Processors,ThreeDsProcessors,PmAuth Processors, FRM Processors
Before
https://github.com/user-attachments/assets/e9b7c884-bdde-4720-aa99-280ae8937ac6
After
https://github.com/user-attachments/assets/17c3cef1-c406-427d-a609-17d5ccd34071
> fix: connector list not updating properly everytime

- src/screens/Surcharge/Surcharge.res
- src/screens/ThreeDSFlow/HSwitchThreeDS.res
The Delete Button is disabled and show the message "You do not have the required permissions to access this module. Please contact your admin."
https://github.com/juspay/hyperswitch-control-center/issues/2135
Locally
> fix: Surcharge and 3DS Delete permission

- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
added granularity options for smart retry tab analytics 
on diff granularity options selected the number of points on graph should change and on diff time range the granuality options should also change [tabs displayed]
> feat: granularity options for smart retry tab analytics

- src/screens/Customers/ShowCustomers.res
for redacted customer, customer details will be all Redacted except the customer id and created datetime, 
below the payment intent and attempts created by that customer will be displayed
redacted customer page view
fixed
- backend changes made for the same (this PR should be deployed after backend is deployed with changes)
- tested locally with local backend branch
- create a new customer, delete it , checkout the redacted customer details page
> chore: redacted customers details page view

- src/components/FilterSelectBox.res
Filters and select box changes
Locally
Before:
After:
> fix: Filter Select Box changes

- config/config.toml
Default config colors of dashboard are added in config ( Temporary )
To support current merchants dashboards.
Locally.
> chore: config colors changes

- src/components/InlineEditInput.res
Fixed Org name updation on outside click.
https://github.com/user-attachments/assets/1f7176b6-ac1f-42d6-91cc-5ae20937c52a
User experience
Attached Video
> fix: org name update

- src/utils/GlobalVars.res
User is logged when org and merchant switch occurs in vault landing page
- switch to a product 
- try to switch to another merchant 
- the merchant should switch successfully
> fix: User is logged when org and merchant switch occurs in product landing page 

- src/entryPoints/AuthModule/Common/CommonAuth.res
- privacy policy not redirecting to correct link for privacy policy
[current link](https://hyperswitch.io/privacyPolicy)
[correct link](https://hyperswitch.io/privacy-policy)
> fix: update privacy policy hyperlink on login page

- src/screens/NewAnalytics/NewAnalyticsUtils.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
- src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
Granularity options for smart retry and refunds tab and minor bug fixes 
The granularit options should visible under smart retry and refunds tabs and the line graph should work properly for all granuality options
> chore: granularity options for smart retry and refunds tab and minor bug fixes 

- public/hyperswitch/Gateway/INESPAY.svg
- src/screens/Connectors/ConnectorTypes.res
- src/screens/Connectors/ConnectorUtils.res
1) Go to connectors, payment processors.
2) You should see Inespay connector , with the respective description and icon.
3) Click on connect , go to the process of connecting the connectors.
4) After the success toast pops up u should see the connector connected in the table.
> feat: Addition of new connectors-Inespay

- src/screens/Analytics/Analytics.res
- src/screens/Analytics/PerformanceMonitor/PerformanceMonitor.res
- src/screens/Home/HomeUtils.res
- src/screens/OMPSwitch/OMPSwitchHelper.res
- src/screens/UserManagement/UserRevamp/ManageUserModal.res
View data button to gradient button
Locally
Before
After
> fix: View data gradient button

- src/Vault/VaultScreens/VaultConnectors/VaultProcessorList.res
- src/components/Filter.res
- src/screens/Connectors/PaymentProcessor/Common/CommonConnectorHelper.res
- src/screens/Home/HomeUtils.res
- src/screens/Transaction/CommonFilters/AmountFilter/AmountFilter.res
- src/screens/Transaction/Order/ShowOrder.res
Fixed alignment of apply button in amount filter
Fixed dropdown width being changed when closing the dropdown in klarna connector
Before
https://github.com/user-attachments/assets/3bba6ebc-9f54-429a-9916-3b5c68b675bd
After
https://github.com/user-attachments/assets/948ed734-5595-4b95-89e3-9c3729fb49e5
Added border to clearall button in filters
Changed Vault Network Tokenization button to always be disabled
Fixed dispute details width
> fix: Fixed ui design bugs

- src/Vault/VaultScreens/VaultConnectors/VaultNetworkTokenisation.res
Set the network Tokenization button to always be disabled and added slack link.
> feat: Added slack link to network tokenization page

- src/screens/Connectors/ConnectorUtils.res
Enabled `NoValnet` in prod
requirement
> chore: novalnet live

- src/screens/RoutingRevamp/AdvancedRoutingUtils.res
- empty type value throwing api error
> chore: fix empty type value causing error in update

- src/entryPoints/HyperSwitchApp.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res
- src/screens/Transaction/Order/HSwitchOrderUtils.res
Added openable ellipses in payments refunds disputes payouts. Added copy in global disputes.
https://github.com/user-attachments/assets/54c2d1b4-e7e2-414c-8184-d123c6f7b25d
UI Fix
Locally
> fix: table ui fixes

- src/screens/Transaction/Order/OrderUIUtils.res
Addition of card discovery filter from FE.
https://github.com/user-attachments/assets/b61c416a-560e-48b2-b795-a9a0c5890bc7
Requirement
Locally
> chore: Addition of card discovery filter in payment ops

- src/RevenueRecoveryScreens/RevenueRecoveryOverview/RecoveryOverviewHelper.res
- src/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryEntity.res
- src/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOrderTypes.res
- src/RevenueRecoveryScreens/RevenueRecoveryOverview/ShowRevenueRecovery.res
> feat: Added attempts table to revenue order details

- cypress/e2e/4-connectors/connector.cy.js
Fix failing connector test
Failure reason: Ellipse UI change in payment ID
Added steps to expand the ID.
> test: fix failing connector test

- src/screens/SDKPayment/SDKPage.res
To resolve #2333 
After changes : 
UI
Locally
> fix: overflow profile in SDK checkout page

- src/screens/Connectors/ConnectorUtils.res
- src/screens/Developer/PaymentSettings/PaymentSettings.res
- src/utils/Mappers/BusinessProfileMapper.res
https://github.com/user-attachments/assets/78b97042-3036-4de3-bacc-d638b4127e65
Go To developers tabs, Click on payment settings .
> chore: Changed custom headers UI

- src/screens/Developer/PaymentSettings/PaymentSettings.res
- src/screens/Developer/PaymentSettings/PaymentSettingsListEntity.res
- src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
- src/screens/Settings/HSwitchSettingTypes.res
- src/screens/Settings/MerchantAccountUtils.res
- src/utils/Mappers/BusinessProfileMapper.res
Added force 3ds challenge field in authentication connector details.
Requirement
https://github.com/user-attachments/assets/37fbfe72-43b9-411a-867e-0a1eebe020c9
> feat: Add force 3ds challenge

- src/screens/Analytics/AuthenticationAnalyticsV2/AuthenticationAnalyticsV2.res
Changed the metrics calculations according to the requirement
Locally
> fix: changed metrics calculations

- src/screens/Routing/AdvancedRouting/AdvancedRouting.res
To resolve #2338 
Tooltips for all icons : 
https://github.com/user-attachments/assets/477b1b64-7c21-4b6d-ba34-4e19b238c5c5
UI improvement
Locally
> fix: Advanced routing responsiveness

- src/APIUtils/APIUtils.res
- src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
- src/screens/Home/HomeUtils.res
- src/screens/Hooks/OMPSwitchHooks.res
- src/screens/OMPSwitch/MerchantSwitch.res
- src/screens/OMPSwitch/OrgSwitch.res
- src/screens/OMPSwitch/ProfileSwitch.res
- src/screens/Routing/ActiveRouting.res
- src/screens/Settings/BusinessMapping/BusinessProfile.res
- src/screens/Sidebar/OrgSidebar.res
- Events for merchant creation, profile creation
- Events for mer and prof switch
- Home page -> Product & Tech blog button has no event
- No event for click on signout
- No event on click of button to submit get production access form
- For payout these three events are named same as routing, change their names
- routing_setup_volume
- routing_setup_rule
- routing_setup_default
events to test 
- Events for merchant creation, profile creation
- Events for mer and prof switch
- Home page -> Product & Tech blog button has no event
- No event for click on signout
- No event on click of button to submit get production access form
- For payout these three events are named same as routing, change their names
- routing_setup_volume
- routing_setup_rule
- routing_setup_default
> chore: additional tracking events

- src/APIUtils/APIUtils.res
- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomerSummary.res
- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersAndTokens.res
- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultPaymentMethodDetailsSidebar.res
- src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
- src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
- src/hooks/AuthHooks.res
- src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/ResultsTableUtils.res
- src/screens/OMPSwitch/OMPSwitchTypes.res
- src/screens/OMPSwitch/OMPSwitchUtils.res
- src/screens/OMPSwitch/ProfileSwitch.res
- src/screens/Payouts/PayoutsUtils.res
- src/screens/Transaction/Order/OrderUIUtils.res
- src/screens/Transaction/Refunds/RefundUtils.res
Added version in user-info
Cannot test as BE changes are needed
> chore: added version in user info

- src/APIUtils/APIUtils.res
> fix: add v1 - authentication analytics

- src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
- src/screens/OMPSwitch/MerchantSwitch.res
- src/screens/OMPSwitch/ProfileSwitch.res
- src/screens/UserManagement/UserRevamp/UserManagementHelper.res
Disabled profile creation for v2 merchants
Backend is not deployed
> chore: disabled profile creation for v2 merchants

- src/screens/Connectors/ConnectorUtils.res
- src/screens/Transaction/Order/OrderEntity.res
Connector Name was showing unknown in Payments Operation Page
It was showing Unknown Connector
Locally via checking 3ds payments
> fix: connector name - unknown issue

- src/screens/Connectors/ConnectorUtils.res
- src/screens/Transaction/Order/OrderEntity.res
Reverts juspay/hyperswitch-control-center#2453
// TODO-  Need to move this a new tab flow where authentication payments can be viewed.
> revert: connector name - unknown issue

- src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsHelper.res
Insights in analytics were not getting sort. FIxed this issue via sorting it.
> fix: sort issue of insights

- src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
- prod intent form is displayed while clicking Get Production Access
> chore: get production access

- src/APIUtils/APIUtils.res
- src/Vault/VaultScreens/VaultDefaultHome.res
- src/Vault/VaultScreens/VaultOnboarding.res
- src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
- src/entryPoints/ProductUtils.res
- src/screens/ConnectorV2/PaymentProcessorSummary.res
- Added Cta in vault home page 
- connector create api change 
-
> fix: vault landing and connector api call changes

- src/RevenueRecovery/RevenueRecoveryContainer/RecoveryConnectorContainer.res
- src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboarding.res
fixed the homa page nagivation and merchant switch is done 
the recovery should fine even after the merchant switch
> fix: merchant switch home page fix

- src/APIUtils/APIUtils.res
- src/Hypersense/HypersenseScreens/HypersenseConfiguration.res
- src/IntelligentRoutingScreens/IntelligentRoutingHome.res
- src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
- src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingLanding.res
- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersTotalDataView.res
- src/Vault/VaultScreens/VaultHome.res
If the user doesn't have create merchant access the v2 create merchant was failing
- if the user doesn't have a create merchant account access , he shouldn't be able to create new merchant for v2 products
> fix: added acl for get started in product home

- src/hooks/AuthHooks.res
Changes for Modularity- Intelligent Routing product 
special feature header required for intelligent routing  `x-feature=dynamo-simulator` so that request is processed by the dynamo for running simulation
> chore: api headers change for Dynamic Routing (Intelligent Routing) (Modularity)

- src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
- src/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
- apis enabled for intelligent rouitng
> chore: enable apis for routing

- src/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
- src/IntelligentRoutingScreens/IntelligentRoutingHelper.res
- src/IntelligentRoutingScreens/IntelligentRoutingReviewFieldsEntity.res
- src/IntelligentRoutingScreens/IntelligentRoutingTransactionsEntity.res
- src/components/Graphs/ColumnGraph/ColumnGraphUtils.res
- src/components/Graphs/LineAndColumn/LineAndColumnGraphTypes.res
- src/components/Graphs/LineAndColumn/LineAndColumnGraphUtils.res
- src/components/Graphs/LineGraph/LineGraphTypes.res
- src/components/Graphs/LineGraph/LineGraphUtils.res
- minor ui fixes in intelligent routing
> chore: routing minor ui fixes

- src/screens/Payouts/PayoutsEntity.res
Payout Processor was having issue in displaying connector name
Via enabling payouts and checking payouts table and connector name was getting filled up.
> fix: payout processor unknown issue

- src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsUtils.res
Calcualation issue in FE for frictionless flow count
Locally value testing
> fix: metrics - frictionless flow count

- src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalytics.res
Resolved issues when applying filters
Added filterValue in the dependency to avoid unnecessary re-renders.
Locally
https://github.com/user-attachments/assets/65252b24-3d9c-4a25-bb0e-b42d652aad22
> fix: resolved issues when applying filters

- src/Recon/ReconApp/ReconSidebarValues.res
- src/Recon/ReconHelper.res
- src/Recon/ReconScreens/ReconOnboarding/ReconOnboarding.res
- src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
- src/Recon/ReconScreens/ReconReports/ReconReports.res
- src/entryPoints/AuthModule/AuthWrapper.res
Recon tabs and mixpanel event changes
> fix: recon tabs and mixpanel event changes

- src/Vault/VaultScreens/VaultHomeUtils.res
Previously both links in the vault page were redirecting to https://docs.hyperswitch.io/about-hyperswitch/payments-modules/vault
but now the correct links have been added
> chore: Changed links in vault config page

- src/Vault/VaultScreens/VaultConnectors/VaultConnectorUtils.res
- src/Vault/VaultScreens/VaultConnectors/VaultProcessorList.res
- src/entryPoints/HyperSwitchApp.res
- src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
- src/screens/OMPSwitch/MerchantSwitch.res
- src/screens/OMPSwitch/OMPSwitchUtils.res
- src/screens/OMPSwitch/ProfileSwitch.res
- src/utils/LogicUtils.res
Changes included in this PR 
- Connector list not getting updated on profile and merchant switch 
- Vault connector list update 
- Duplicate values in merchant dropdown 
- Go to connectors list and switch profiles , list for that profile should be visible
> fix: Connector list not updated on profile switch fix

- src/screens/Transaction/Order/HSwitchOrderUtils.res
- src/utils/GlobalVars.res
To resolve #2399 
Better user experience
Locally
> fix: operations external url

- src/Recon/ReconScreens/ReconConfiguration/Final/Final.res
- src/Recon/ReconScreens/ReconReports/ReconReports.res
- src/Recon/ReconScreens/ReconReports/ReportsExceptionTableEntity.res
- src/Recon/ReconScreens/ReconReports/ReportsTableEntity.res
- src/Recon/ReconScreens/ReconReports/ReportsTypes.res
- src/Recon/ReconScreens/ReconReports/ShowAllReports.res
- src/Recon/ReconScreens/ReconReports/ShowReconExceptionReport.res
- src/Recon/ReconScreens/ReconReports/TempReportsData/ReportsData.res
Removed actions from the reports and exception tables, 
Text changes
Date changes in the report and exceptions
Download recon report with recon_id and csv file date fix
Locally
Need to change the entire data will be doing it separately
> fix: removed actions, text changes, date changes

- src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsUtils.res
updated the billing connector metadata config field 
billing connector auth page should ask for site name for chargebee
> chore: billing connector metadata update

- src/APIUtils/APIUtils.res
- src/container/NewAnalyticsContainer.res
- src/screens/Analytics/Analytics.res
- src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
- src/screens/Analytics/PerformanceMonitor/PerformanceMonitor.res
- src/screens/Home/HomeUtils.res
- src/screens/Home/ProdIntent/ProdVerifyModal.res
- src/screens/Processors/ProcessorCards.res
- src/screens/Sidebar/Sidebar.res
- src/utils/LogicUtils.res
Addedfollowing mixpanel events
1)When production access form submit button is clicked. (create_get_production_access_request)
2)On voluntary signout-(user_signout_manual)
3)When + connect button is clicked on processors,event is specific to processor(connect_processor_adyen_payoutconnectors) (connect_processor_adyen_pm_authentication_processor)(connect_processor_taxjar_tax_processor)
3)API key button click from homepage(redirect_to_api_keys)
> chore: Added general mixpanel events

- src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
- src/IntelligentRoutingScreens/IntelligentRoutingHelper.res
- src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
- src/components/Graphs/LineGraph/LineGraphTypes.res
- src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsUtils.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedUtils.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRateUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
- src/utils/LogicUtils.res
- src/utils/LogicUtilsTypes.res
> fix: analytics insights breaking fix

- src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
Added analytics overview mixpanel
on landing overview page -> recon_analytics_overview
Better tracking.
Locally
> chore: Add mixpanel for recon analytics

- src/Vault/VaultContainer/VaultContainer.res
- src/Vault/VaultScreens/VaultConnectors/VaultConnectorHelper.res
- src/Vault/VaultScreens/VaultConnectors/VaultProcessorCards.res
- src/screens/ConnectorV2/PaymentProcessorSummary.res
Before V1 list was being populated in vault
after
https://github.com/user-attachments/assets/7b92b4c2-34aa-4a42-943e-74961d3b6df3
Connector update was not being reflected in vault
after fix
https://github.com/user-attachments/assets/a4552b71-01aa-4c54-881d-52059fc085ef
Also added vault_request_processor mixpanel event in new request a processor design
- [x  I reviewed submitted code
> fix: fixed vault bugs

- src/Vault/VaultScreens/VaultConnectors/VaultProcessorList.res
- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomerSummary.res
- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultPaymentMethodDetailsSidebar.res
https://github.com/user-attachments/assets/b7765721-d6ad-4543-b2cf-76a48320a054
https://github.com/user-attachments/assets/1539864a-7b5c-4f38-b4fc-e6e99b7b5da5
> chore: added scrollbar in vault tables

- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersTotalDataView.res
- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersType.res
After fix
https://github.com/user-attachments/assets/404e58e4-8699-4a95-901e-aedfa58afbd6
- [x  I reviewed submitted code
> fix: Render glitch of total customers and total token component

- src/Vault/VaultScreens/VaultConnectors/VaultProceesorReview.res
- src/Vault/VaultScreens/VaultOnboarding.res
https://github.com/user-attachments/assets/6c9efbb8-e5c7-4c17-96dd-238cc686876c
Also
fixed the webhhok step url and button allignment,font and Review and connect step subheading font colour
> fix: webhook step horizontally scrollable

- src/components/Graphs/LineGraph/LineGraphTypes.res
- src/components/Graphs/LineGraph/LineGraphUtils.res
added options for inactive line state
currently set to false, will be used later
no UI changes
> chore: updated graph options

- src/Hypersense/HypersenseScreens/HypersenseConfiguration.res
- src/Hypersense/HypersenseScreens/HypersenseHome.res
- src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
- src/entryPoints/ProductUtils.res
Changed hypersense to Cost observability 
- Sidebar should show cost observability 
- mixpanel should have cost observability  rather than hypersense
> fix: hypersense product name change to cost observability

- src/entryPoints/HyperSwitchApp.res
- src/screens/Home/ProdIntent/ProdVerifyModal.res
- src/screens/Home/ProdIntent/ProdVerifyModalUtils.res
The warnings which were coming before
> fix: browser console  warnings

- src/entryPoints/ProductTypes.res
- src/entryPoints/ProductUtils.res
- src/entryPoints/SidebarValues.res
- src/screens/PayoutRouting/PayoutHistoryTableEntity.res
- src/screens/Routing/HistoryEntity.res
- removed APM from product types
- removing redundant code
- no visible UI change
> Chore: Remove apm from product types

- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersAndTokens.res
- src/Vault/VaultScreens/VaultOnboarding.res
- tailwind.config.js
https://github.com/user-attachments/assets/19051e93-1805-4a51-b9a2-5add7a4e2f1a
https://github.com/user-attachments/assets/2c06620a-78bf-421d-bac2-b786b4619682
> fix: fixed vault 13 inch screen ui bugs

- src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
- src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingHelper.res
- src/components/Graphs/LineAndColumn/LineAndColumnGraphTypes.res
- src/components/Graphs/LineAndColumn/LineAndColumnGraphUtils.res
- src/components/Graphs/LineGraph/LineGraphTypes.res
- src/components/Graphs/LineGraph/LineGraphUtils.res
- src/components/Graphs/PieGraph/PieGraphUtils.res
- src/context/MatchMedia.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedUtils.res
- src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRateUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
- src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
- src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
- tailwind.config.js
implemented responsiveness in intelligent routing charts 
removed redundant code
custom y axis min value for line chart
https://github.com/user-attachments/assets/1606f65c-ee5d-4969-9902-e27478fe87a1
> chore: made charts responsive

- src/entryPoints/HyperSwitchApp.res
Remove global search for modular products.
https://github.com/juspay/hyperswitch-control-center/issues/2745
Locally
https://github.com/user-attachments/assets/fdf41caa-90d5-4dad-81a7-bf5cf06273ad
> chore: show global search bar only for orchestrator

- src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorsSummary.res
- src/entryPoints/ProductUtils.res
- src/screens/DefaultHome/DefaultHomeUtils.res
recovry product name changed to "revenue recovery"
> chore: recovery product name change

- src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryEntity.res
- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersEntity.res
- src/components/TableUtils.res
- src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
- src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
- src/screens/Connectors/PaymentProcessor/ConnectorTableUtils.res
- src/screens/Connectors/PayoutProcessor/PayoutProcessorTableEntity.res
- src/screens/Connectors/TaxProcessor/TaxProcessorTableEntity.res
- src/screens/Customers/CustomersEntity.res
- src/screens/Developer/APIKeys/DeveloperUtils.res
- src/screens/Developer/APIKeys/PublishableAndHashKeySection.res
- src/screens/Helpers/HelperComponents.res
- src/screens/OMPSwitch/OMPSwitchHelper.res
- src/screens/Sidebar/OrgSidebar.res
- src/screens/Transaction/Disputes/DisputesEntity.res
- src/screens/Transaction/Order/OrderEntity.res
- src/screens/Transaction/Refunds/RefundEntity.res
- src/utils/LogicUtils.res
Display value type in the component is changed to Some or None case
https://github.com/juspay/hyperswitch-control-center/issues/2807
No testing required as it is a refactoring
> refactor: copy text custom component displayValue type change

- src/Recon/ReconApp/ReconApp.res
- src/Recon/ReconApp/ReconSidebarValues.res
- src/Recon/ReconContainer/ReconConfigurationContainer.res
- src/Recon/ReconContainer/ReconOverviewContainer.res
- src/Recon/ReconScreens/ReconConfiguration/Final/Final.res
- src/Recon/ReconScreens/ReconConfiguration/ReconConfiguration.res
- src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
- src/entryPoints/ProductUtils.res
Recon navigation and url changes 
Locally
> chore: recon navigation and url changes

- src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
- src/screens/Analytics/RefundsAnalytics/RefundsAnalytics.res
removed passing of extra metrics for anaytlics table data display 
data should be displyad correct that group-by columns should only includes the values which value is present
> fix: analytics group by currency NA row fix

- src/APIUtils/APIUtils.res
- src/screens/Developer/Webhooks/Webhooks.res
- changed merchant level api to profile level
- changed GET to POST api
- query params now being passed in payload
> chore: changed merchant level api endpoint to profile level

- src/components/SelectBox.res
- src/components/Table.res
- src/screens/Sidebar/Sidebar.res
Changed the colour for all scrollbar.
Changed sidebar scrollbar to only appear when u hover over it
Increased table horizontal scrollbar thickness
https://github.com/user-attachments/assets/26c17b37-5afc-42ca-8dd9-b036e2370e04
https://github.com/user-attachments/assets/6dd189ce-e21f-48fd-b536-f3689bb2ccc5
- Wherever scrollbar appears(vertical or horizontal) in the dashboard it should be of this new colour.
- Horizontal scrollbar in tables should be of increased thickness.
> chore: Changed scrollbar colour and state

- src/Hypersense/HypersenseScreens/HypersenseHome.res
- src/Interface/ConnectorInterface/ConnectorInterfaceUtils.res
- src/screens/Connectors/ConnectorTypes.res
- src/screens/Connectors/PaymentProcessor/ConnectPayPalFlow/MenuOptionForPayPal.res
- src/screens/Connectors/PaymentProcessor/ConnectorPreviewHelper.res
- src/screens/Connectors/PaymentProcessor/ConnectorUpdateAuthCreds.res
https://github.com/user-attachments/assets/8821e8a5-913f-48d8-96fa-a18caf8c46c3
Now connector label will show up in credentials for every connector.
> fix: Fixed ctp_vissa connector not updating

- src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorsSummary.res
- src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res
- src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryEntity.res
- src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOverview.res
- src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/ShowRevenueRecovery.res
- src/components/TableUtils.res
- src/fragments/ConnectorFragments/ConnectorHelperV2.res
- src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
- src/screens/Connectors/PaymentProcessor/ConnectorPaymentMethod.res
- src/screens/Connectors/PayoutProcessor/PayoutProcessorPaymentMethod.res
- src/screens/Home/ProdIntent/ProdIntentForm.res
- src/screens/Home/ProdIntent/ProdVerifyModal.res
- src/screens/OMPSwitch/OMPSwitchHelper.res
- src/screens/SDKPayment/SDKPage.res
- src/screens/SDKPayment/WebSDK.res
Removed warnings for better development
Console warnings removed
> chore: remove warnings

- src/screens/Connectors/PaymentProcessor/ConnectorUpdateAuthCreds.res
Added success toast after updating the connector credentials
https://github.com/juspay/hyperswitch-control-center/issues/2868
Locally
Update the connector credentials, success toast with Details Updated! should appear.
> fix: added success toast after updating connector credentials

- tailwind.config.js
Adds responsive utilities for various letter-spacing values including compressed, condensed, normal, expanded, and extended
Typography changes
Locally
> chore: Addition of letter spacing in tailwind

- src/screens/Developer/Webhooks/Webhooks.res
ui text update for webhooks not configured
locally
> fix: webhook url not configured text update

- src/screens/OMPSwitch/MerchantSwitch.res
- src/screens/OMPSwitch/OMPSwitchUtils.res
Fix for when the merchant name is same then it merchant list was not getting called in production 
- Local dashboard
> fix: merchant name issue fix

- src/components/ColorPickerInput.res
- src/screens/SDKPayment/FormSection/CheckoutDetails.res
- src/screens/SDKPayment/FormSection/ThemeCustomization.res
- src/screens/SDKPayment/PreviewSection/SDKPayment.res
- tailwind.config.js
So let's say when client secret is expired and then someone click on Show Preview of Theme Customization the SDK will fail.
Locally
> chore: api call for payments - theme customization & bg-color added

- config/config.toml
- src/entryPoints/HyperSwitchEntry.res
- src/entryPoints/configs/HyperSwitchConfigTypes.res
- src/utils/DOMUtils.res
Add clarity script for tracking 
The script should be added under the head tag while checking in elements in the browser
> feat: add clarity tracking

- src/Orchestration/OrchestrationApp.res
- src/entryPoints/HyperSwitchApp.res
- src/entryPoints/SidebarValues.res
- src/screens/NewAnalytics/NewAnalyticsContainerUtils.res
- src/screens/NewAnalytics/NewAnalyticsTypes.res
Highlight a side bar values in insights tab changed 
when we move to second and third tab of insights the side bar should highlights the subsection value
> fix: insights side bar highlight fix

- src/screens/Routing/AdvancedRouting/AdvancedRoutingUIUtils.res
Button overflow in safari browser
https://github.com/juspay/hyperswitch-cloud/issues/9439
Locally
Before:
After:
> fix: safari select buttons change in rule based routing

- tailwind.config.js
> fix: soft color correction

- src/screens/NewAnalytics/NewAnalyticsHelper.res
Banner text change on toggle.
https://github.com/user-attachments/assets/ddd17e09-d8ef-47ed-9e94-eff78c59f141
Design 
Locally
> chore: banner text design for sample analytics

- src/screens/NewAnalytics/InsightsHelper.res
Add metadata in mixpanel to add more context about the usage of sample analytics.
Deeper analytics insights
Locally
> chore: Add metadata in mixpanel sample analytics

- src/screens/Connectors/ConnectorUtils.res
Enabled `Redsys` in prod
requirement
> chore: redsys connector live

- cypress/e2e/4-connectors/connector.cy.js
- cypress/support/pages/workflow/paymentRouting/PaymentRouting.js
> test: fix failing tests

- src/screens/Connectors/PayoutProcessor/PayoutProcessorPaymentMethod.res
payout processor unknown name in edit pmt page
Locally
Before
After
> fix: payout processor unknown name in edit pmt

- src/screens/SDKPayment/PreviewSection/CheckoutForm.res
SDK was showing Something went wrong
Wrong info getting shared
Locally
> fix: sdk issue description

- src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
- currently we are converting the email to lowercase and sending to backend because earlier backend did not had email case conversion
- now we do not require this change
> chore: removed frontend email case conversion

- src/screens/Routing/DebitRouting/DebitRoutingConfigureModal.res
UI change :
Requirement
Locally
> fix: Debit routing configure modal

- cypress/e2e/6-workflow/PaymentRouting.cy.js
- cypress/support/pages/workflow/paymentRouting/PaymentRouting.js
Fix failing routing tests caused by UI changes in routing page.
ref: https://github.com/juspay/hyperswitch-control-center/pull/3025
> test: fix failing routing tests

- src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryData.res
- src/utils/LogicUtils.res
This pull request introduces a utility module, `DummyKeyGen`, to dynamically generate randomized API keys and secrets, replacing hardcoded values in the `RevenueRecoveryData.res` file. This change improves security and flexibility by ensuring sensitive data is not hardcoded.
This pull request introduces a new utility function, `randomString`, to generate random alphanumeric strings and integrates it into the `RevenueRecoveryData.res` file to dynamically create API keys and other identifiers. The changes improve security by replacing hardcoded sensitive values with dynamically generated ones.
* **Dynamic API Key Generation**: Added a new `generateApiKey` function in `RevenueRecoveryData.res` to generate API keys and other sensitive values dynamically using the `randomString` utility, …
> chore: removed recovery hard coded dummy keys

- src/screens/PayoutRouting/PayoutRoutingStack.res
To maintain consistency with payment routing UI, following changes are made
Before:
After:
Before:
https://github.com/user-attachments/assets/40038244-0d42-4159-a1a8-dddcfa6d7470
After:
https://github.com/user-attachments/assets/8893d07e-197b-4900-ab81-a9944f96d48c
> fix: swap tabs in payout routing

- src/screens/DefaultHome/DefaultHome.res
- src/screens/DefaultHome/DefaultHomeTypes.res
- src/screens/DefaultHome/DefaultHomeUtils.res
Update the urls in the v2 home page
User cannot navigate among different product without switching, when clicking on different product, it was showing unauthorized and going to loop in case of orchestration.
https://github.com/juspay/hyperswitch-control-center/issues/3144
Locally
> fix: url updates for the default home page

- src/screens/Connectors/ConnectorUtils.res
- src/screens/Helpers/HelperComponents.res
Add 3ds secure io name in list
> chore: Not Found for 3ds secure io

- src/screens/Routing/ActiveRouting.res
- src/screens/Routing/RoutingUtils.res
to resolve #3163 
bugfix
locally
> fix: Debit routing present in Payout routing

- public/hyperswitch/icons/static-retry.svg
- src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetriesComparision/RetriesComparisionAnalytics.res
- src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetriesComparision/RetriesComparisionAnalyticsUtils.res
- src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/SmartRetryStrategy/SmartRetryStrategyAnalytics.res
- src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/SmartRetryStrategy/SmartRetryStrategyAnalyticsTypes.res
- src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/SmartRetryStrategy/SmartRetryStrategyAnalyticsUtils.res
- src/components/Graphs/LineScatterGraph/LineScatterGraphTypes.res
- src/components/Graphs/LineScatterGraph/LineScatterGraphUtils.res
- src/screens/NewAnalytics/InsightsTypes.res
This pull request introduces enhancements to the analytics graphs in the Revenue Recovery module, focusing on improving visual representation and adding contextual information. Key changes include the integration of SVG icons, dynamic legend formatting, and tooltips with enriched details.
* Updated `xKey` values in `RetriesComparisionAnalytics.res` and `SmartRetryStrategyAnalytics.res` to use SVG icons (`/icons/static-retry.svg` and `/icons/smart-retry.svg`) for better visual distinction in graphs.
* Added support for `symbol` in `LineScatterGraphTypes.lineScatterGraphPayload` to allow custom markers, such as SVG icons, in scatter plots.
* Replaced static legend formatting with dynamic `valueFormatter` that incorporates SVG icons or color markers based on graph data.
* Enhanced …
> chore: recovery graphs minor ui tweaks

- src/screens/Developer/APIKeys/DeveloperUtils.res
Changed name from "Merchant Code With Name" to "Merchant Category Code"
> chore: Changes merchant category code dropdown name

- src/components/Filter.res
- src/screens/Analytics/Analytics.res
- src/screens/Analytics/HSAnalyticsUtils.res
- src/screens/GenerateReports/GenerateReport.res
- src/screens/NewAnalytics/NewAuthenticationAnalytics/AuthenticationSummary/AuthenticationSummary.res
- src/screens/NewAnalytics/NewAuthenticationAnalytics/ExemptionGraphs/ExemptionGraphsUtils.res
- src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalytics.res
- src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsHelper.res
- src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsUtils.res
- Disabled the "Generate Reports" button while using sample data.
- Made the filter dropdown menu scrollable to improve usability when there are many filter options.
- Fixed an issue where the Dashboard frontend was sending boolean filter values as strings. Updated the logic to ensure correct data types are sent in the request payload.
I have tested it in local setup.
> fix: make filter menu scrollable and fix filter type issues

- src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigEntity.res
- src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigSettings.res
- src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigUtils.res
Issues fixed: (https://github.com/juspay/hyperswitch-cloud/issues/9995)
1. acquirerAssignedMerchantId and merchantName field will accept only alphanumeric input
2. acquirerBin validation and error message corrected
3. acquirerFraudRate field is required to submit the form
TESTED LOCALLY
https://github.com/user-attachments/assets/492aa023-3e86-4415-8669-9c00173fd359
> fix: improvement and bug fixes

- src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
- src/screens/Connectors/PaymentProcessor/ConnectorTableUtils.res
- src/screens/Connectors/PayoutProcessor/PayoutProcessorTableEntity.res
- src/screens/Connectors/TaxProcessor/TaxProcessorTableEntity.res
- src/screens/Connectors/ThreeDsProcessors/ThreeDsTableEntity.res
> refactor: remove unused code

- src/OrchestrationV2/OrchestrationV2Screens/Connectors/DummyProcessorModalV2.res
- src/OrchestrationV2/OrchestrationV2Screens/Connectors/PaymentConnectors.res
- src/OrchestrationV2/OrchestrationV2Screens/Connectors/PaymentProcessorCards.res
- src/screens/Processors/ProcessorCards.res
- sidebar hidden in connectors configuration fix
> fix: sidebar hidden fix

- src/Interface/ConnectorInterface/ConnectorInterfaceTableEntity.res
- src/OrchestrationV2/OrchestrationV2Screens/Connectors/PaymentConnectors.res
- src/Vault/VaultScreens/VaultConnectors/VaultConnectorEntity.res
- src/Vault/VaultScreens/VaultConnectors/VaultProcessorList.res
- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersAndTokens.res
- src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersEntity.res
- src/components/priority-logics/AddPLGateway.res
- src/screens/Connectors/FraudAndRisk/FRMTableUtils.res
- src/screens/Connectors/PaymentProcessor/ConnectorList.res
- src/screens/Connectors/PaymentProcessor/ConnectorPreview.res
- src/screens/Routing/AdvancedRouting/AddRuleGateway.res
- src/screens/Routing/AdvancedRouting/AdvancedRouting.res
- src/screens/Routing/AdvancedRouting/RulePreviewer.res
- src/screens/Routing/DefaultRouting/DefaultRouting.res
- src/screens/Routing/VolumeSplitRouting/VolumeSplitRoutingPreviewer.res
- utilising common entity file for v1 and v2 connectors list table
> chore: common entity for connector list loaded table

- src/ReconEngine/ReconEngineScreens/ReconEngineConnection/ReconEngineConnectionDisplay.res
- src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionStaging/ReconEngineExceptionStaging.res
- src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionTransaction/ReconExceptionTransaction.res
- src/ReconEngine/ReconEngineScreens/ReconEngineFileManagement/ReconEngineFileManagementTypes.res
- src/ReconEngine/ReconEngineScreens/ReconEngineFileManagement/ReconEngineFileManagementUtils.res
- src/ReconEngine/ReconEngineScreens/ReconEngineFileManagement/ReconEngineIngestion/ReconEngineFileUploadModal.res
- src/ReconEngine/ReconEngineScreens/ReconEngineFileManagement/ReconEngineIngestion/ReconEngineIngestionHistory.res
- src/ReconEngine/ReconEngineScreens/ReconEngineFileManagement/ReconEngineTransformation/ReconEngineTransformationDetails/ReconEngineTransformationStagingEntries.res
- src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverview.res
- src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewDetails/ReconEngineOverviewDetailsComponents/ReconEngineOverviewCardDetails.res
- src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewDetails/ReconEngineOverviewDetailsComponents/ReconEngineOverviewTransactions.res
- src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewUtils.res
- src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/EntriesTableEntity.res
- src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactions.res
- src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsHelper.res
- src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsTypes.res
- src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsUtils.res
- src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/TransactionsTableEntity.res
- Added discarded_at statuses in transactions and entries
- Initialize all date filters to past 180 days (6months) by default
- Truncate fields and values in the connections screen
- Listing only manual upload configs in the upload 
- Added Missing in target account in the overview page
- Showing the absolute variance instead of positives and negatives
Locally
> fix: recon bugs

- public/hyperswitch/Gateway/CHECKBOOK.svg
- src/screens/Connectors/ConnectorTypes.res
- src/screens/Connectors/ConnectorUtils.res
Add new connector checkbook
https://github.com/user-attachments/assets/bd273f47-08cd-4156-ac83-89104457bafe
https://github.com/juspay/hyperswitch-control-center/issues/3437
Locally
> feat: add new connector `CheckBook`

- cypress/support/pages/homepage/HomePage.js
> fix: Fix cypress tests

- src/ReconEngine/ReconEngineScreens/ReconEngineConnection/ReconEngineConnection.res
- src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionTransaction/ReconExceptionTransactionUtils.res
- src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptions.res
- src/ReconEngine/ReconEngineScreens/ReconEngineFileManagement/ReconEngineIngestion/ReconEngineIngestion.res
- src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverview.res
- src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewSummary/ReconEngineOverviewSummaryComponents/ReconEngineOverviewSummaryFlowDiagram.res
- src/ReconEngine/ReconEngineScreens/ReconEngineRules/ReconEngineRule.res
- src/ReconEngine/ReconEngineScreens/ReconEngineRules/ReconEngineRuleDetails.res
- src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactions.res
- src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsUtils.res
Remove subtitles and arrange the page headings, increase zoom out for small screens, renaming source and targets
Locally
> chore: recon engine remove subtitles and arrange the page heading

- src/ReconEngine/ReconEngineApp/ReconEngineApp.res
- src/ReconEngine/ReconEngineApp/ReconEngineSidebarValues.res
- src/ReconEngine/ReconEngineContainer/ReconEngineAccountsContainer.res
- src/ReconEngine/ReconEngineScreens/ReconEngineAccounts/ReconEngineAccountsSources/ReconEngineAccountsSources.res
- src/ReconEngine/ReconEngineScreens/ReconEngineAccounts/ReconEngineAccountsTransformation/ReconEngineAccountsTransformation.res
- src/ReconEngine/ReconEngineScreens/ReconEngineAccounts/ReconEngineAccountsTransformedEntries/ReconEngineAccountsTransformedEntries.res
Recon engine accounts section folder setup
Locally
> feat: recon engine accounts section folder setup

- src/Orchestration/OrchestrationApp.res
- src/container/AnalyticsContainer.res
- src/screens/Home/HomeUtils.res
- src/screens/NewAnalytics/RoutingAnalytics/LeastCostRoutingAnalytics/LeastCostRoutingAnalyticsDistribution/LeastCostRoutingAnalyticsDistribution.res
- src/screens/NewAnalytics/RoutingAnalytics/LeastCostRoutingAnalytics/LeastCostRoutingAnalyticsDistribution/LeastCostRoutingAnalyticsDistributionComponents/LeastCostRoutingAnalyticsDistributionPieGraph.res
- src/screens/NewAnalytics/RoutingAnalytics/LeastCostRoutingAnalytics/LeastCostRoutingAnalyticsDistribution/LeastCostRoutingAnalyticsDistributionUtils.res
- src/screens/NewAnalytics/RoutingAnalytics/LeastCostRoutingAnalytics/LeastCostRoutingSummary/LeastCostRoutingAnalyticsSummaryTable.res
- src/screens/NewAnalytics/RoutingAnalytics/OverallRoutingAnalytics/RoutingAnalyticsDistribution/RoutingAnalyticsDistribution.res
- src/screens/NewAnalytics/RoutingAnalytics/OverallRoutingAnalytics/RoutingAnalyticsSummary/RoutingAnalyticsSummary.res
- src/screens/NewAnalytics/RoutingAnalytics/RoutingAnalytics.res
- src/screens/NewAnalytics/RoutingAnalytics/RoutingAnalyticsTypes.res
- src/screens/NewAnalytics/RoutingAnalytics/RoutingAnalyticsUtils.res
On omp switch the tab isnt switched to Overall routing
https://github.com/user-attachments/assets/7ebf6424-e754-4460-ace8-7e327cd7c199
Fixed Pie chart alignment and Y axis label in tooltip of savings graph
https://github.com/user-attachments/assets/2022ab96-2e5d-43b2-bca2-f6b3d8514ed0
> fix: fixed least cost routing analytics distribution bugs

- src/screens/Connectors/ConnectorTypes.res
- src/screens/Connectors/ConnectorUtils.res
Gigadat addition as payout connector.
Requirement
> feat: gigadat payout connector
