package.json
src/screens/HyperSwitch/UserManagement/HSwitchUserRoleEntity.res

fix: dead code removal

---

.githooks/commit-msg
.github/PULL_REQUEST_TEMPLATE.md
.gitignore
README.md
src/entryPoints/hyperswitch/EntryPointUtils.res
src/entryPoints/hyperswitch/Provider/GlobalProvider.res
src/entryPoints/hyperswitch/Provider/ProviderHelper.res
src/entryPoints/hyperswitch/Provider/ProviderTypes.res

fix: commit-msg file changes & README.md file updated.

---

src/components/ButtonGroupIp.res
src/components/CsvFileUpload.res
src/components/CustomCharts/HighchartBarChart.res
src/components/CustomCharts/LineChartUtils.res
src/components/DatePicker.res
src/components/DistributionDonut/DistributionDonut.res
src/components/ExportTable.res
src/components/HSwitchSingleStatWidget.res
src/components/HighchartFunnelChart.res
src/components/InputFields.res
src/components/InputFields.resi
src/components/RedirectSearchInput.res
src/components/SelectBox.res
src/components/SelectBox.resi
src/components/form/MultipleTextInput.res
src/components/form/SelectBoxCard.res
src/entities/analytics/EulerAnalyticsLogUtils.res
src/genericUtils/Identity.res
src/libraries/Highcharts.res
src/libraries/SankeyHighcharts.res
src/screens/HyperSwitch/Analytics/Analytics.res
src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
src/screens/HyperSwitch/SDKPayment/SDKPage.res
src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
src/screens/analyticsScreens/AnalyticsCommonComponents.res

feat: Identity file changes

---

src/screens/HyperSwitch/Order/HSwitchOrderUtils.res
src/screens/HyperSwitch/Order/OrderEntity.res
src/screens/HyperSwitch/Order/ShowOrder.res

feat: Refund enable for Partially Captured Payments

---

src/components/ButtonGroupIp.res
src/components/Chip.res
src/components/CollapsableTableRow.res
src/genericUtils/BreadCrumbNavigation.res
src/screens/HyperSwitch/Routing/AdvancedRouting/RoutingPreviewer.res
src/screens/HyperSwitch/RoutingRevamp/AddRuleGateway.res
src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
src/screens/HyperSwitch/Utils/HSSelfServeSidebar.res

refactor: Refactoring key errors

---

src/screens/HyperSwitch/Order/OrderEntity.res
src/screens/HyperSwitch/Order/OrderUIUtils.res
src/screens/HyperSwitch/Order/ShowOrder.res
src/screens/HyperSwitch/PaymentLogs/PaymentLogs.res

feat: Show Details Paymentb Enhancement

---

src/screens/HyperSwitch/PaymentLogs/PaymentLogs.res

feat: added path and api method in audit logs

---

src/screens/HyperSwitch/Sidebar/Sidebar.res
src/screens/HyperSwitch/Sidebar/SidebarTypes.res
src/screens/HyperSwitch/Utils/HSwitchGlobalSearchBar.res
src/screens/HyperSwitch/Utils/PageLoaderWrapper.res

fix: Removed Sublevel remote link type & Pageloader CSS fixes.

---

src/screens/HyperSwitch/APIUtils/APIUtils.res
src/screens/HyperSwitch/APIUtils/APIUtilsTypes.res

The code now uses the apiPrefix only once instead of writing it again and again.
Make code more readable and reduce redundancy.

refactor: apiUtils file to use the apiPrefix once only

---

CHANGELOG.md
src/components/EntityScaffold.res
src/components/UnauthorizedPage.res
src/components/form/BoolInput.res
src/context/FormAuthContext.res
src/entryPoints/hyperswitch/HyperSwitchApp.res
src/entryPoints/hyperswitch/SidebarValues.res
src/screens/HyperSwitch/UserManagement/PermissionUtils.res
src/screens/login/AuthTypes.res

chore: Added Access Type & Remove the Read & ReadWrite Type

---

src/components/priority-logics/PriorityLogicUtils.res
src/screens/HyperSwitch/Routing/AdvancedRouting/RoutingPreviewer.res
src/screens/HyperSwitch/Routing/HistoryEntity.res
src/screens/HyperSwitch/Routing/PriorityRouting.res
src/screens/HyperSwitch/Routing/RoutingTypes.res
src/screens/HyperSwitch/Routing/RoutingUtils.res
src/screens/HyperSwitch/Routing/VolumeSplitRouting.res
src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUtils.res
src/screens/HyperSwitch/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
src/screens/HyperSwitch/Surcharge/Surcharge.res
src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res

refactor: routing types and utils

---

src/screens/ThreeDSFlow/HSwitchThreeDS.res

fix: Added delete 3ds rule

---

src/screens/SDKPayment/WebSDK.res

Redirect to be send inside confirm params that's why it was not able to redirect.
Via making a payment it redirected.

fix: redirect to be send inside confirm params

---

src/components/Navbar.res
src/context/AuthInfoProvider.res
src/context/UserPrefContext.res
src/entryPoints/AuthModule/AuthProviderTypes.res
src/entryPoints/AuthModule/AuthUtils.res
src/entryPoints/AuthModule/AuthWrapper.res
src/entryPoints/AuthModule/BasicAuth/BasicAuthWrapper.res
src/entryPoints/AuthModule/Common/CommonAuthHooks.res
src/entryPoints/AuthModule/SSOAuth/SSODecisionScreen.res
src/entryPoints/AuthModule/TwoFaAuth/TwoFaDecisionScreen.res
src/entryPoints/AuthModule/TwoFaAuth/TwoFaTypes.res
src/entryPoints/AuthModule/TwoFaAuth/TwoFaUtils.res
src/entryPoints/AuthModule/UserInfoScreen.res
src/hooks/AuthHooks.res
src/screens/Home/Home.res
src/screens/Home/HomeV2.res
src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
src/screens/SwitchMerchant/SwitchMerchant.res

chore: sso new enum addition

---

config/config.toml
src/context/AuthInfoProvider.res
src/entryPoints/AuthModule/AuthModuleHooks.res
src/entryPoints/AuthModule/AuthUtils.res
src/entryPoints/AuthModule/AuthWrapper.res
src/entryPoints/AuthModule/Common/CommonAuth.res
src/entryPoints/AuthModule/Common/CommonAuthHooks.res
src/entryPoints/AuthModule/PreLoginModule/AuthSelect.res
src/entryPoints/AuthModule/SSOAuth/SSOTypes.res
src/entryPoints/AuthModule/SSOAuth/SSOUtils.res
src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuthScreen.res

chore: allow singup based on auth methods

---

src/entryPoints/AuthModule/AuthUtils.res
src/entryPoints/AuthModule/AuthWrapper.res
src/entryPoints/AuthModule/PreLoginModule/AuthSelect.res
src/entryPoints/AuthModule/SSOAuth/SSOTypes.res
src/entryPoints/AuthModule/SSOAuth/SSOUtils.res

Previously, the `auth/select` API required auth_id as a mandatory request parameter. However, this caused the API to fail when users selected 'Continue with Hyperswitch' from an email. To address this, the backend team has made auth_id optional in the request body. Consequently, the frontend has also adjusted the request structure and made the auth_id parameter optional to support this change.

fix: accept invite flow breaking for non-auth users 

---

src/entryPoints/AuthModule/BasicAuth/BasicAuth.res
src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res

Signup button not working in sbx as there is no password field when email feature flag is on

fix: Sign up button not working for sbx

---

config/config.toml
src/entryPoints/FeatureFlagUtils.res
src/entryPoints/HyperSwitchApp.res
src/entryPoints/SidebarValues.res

Previously, the recon module was controlled by two feature flags: recon_v2 and recon. With this change, the reconciliation module with subitems will be shown to users who have the recon feature enabled and an active recon status. The recon_v2 feature flag will no longer be needed. 
**NOTE**: This will not affect users in live mode since recon will not be enabled in production.

chore: removing recon_v2 feature flag

---

src/screens/Order/OrderEntity.res

Currently the operation address fields are contracted based on multiple keys , this pr will remove first name and last name from the fields used in the address

fix: remove name from address fields

---

src/components/FilterSelectBox.res
src/components/SelectBox.res
src/components/SelectBox.resi

Earlier row level customisation was not possible with select box for a specific row . With this change row level customisation will be possible by passing the custom css in `customRowClass` param. 
For eg : i have passed bg-color = blue just for 3ds 
Cannot be tested at the moment since it's a chore-level change.

chore: extra param for row level customization with select box

---

src/entryPoints/HyperSwitchApp.res
src/entryPoints/SidebarValues.res
src/screens/Connectors/ConnectorTypes.res
src/screens/Connectors/ConnectorUtils.res
src/screens/PMAuthenticationProcessor/PMAuthenticationConnectorList.res
src/screens/PMAuthenticationProcessor/PMAuthenticationHome.res
src/screens/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
src/screens/PMAuthenticationProcessor/PMAuthenticationTypes.res

PM Authentication Processor new flow

feat: addition of pm authentication processor new flow

---

package.json
src/components/HSwitchSingleStatWidget.res

1. In newer versions Mixpanel.init is deprecated , hence pinned the version as of to `2.45.0`
2. Unresolved data is being sent to ApexCharts, preventing chart rendering and blocking the entire thread. Consequently, API responses are delayed despite a 200 status code.

fix: commented apex charts and pinned mixpanel version

---

src/screens/Order/OrderRefundForm.res

Earlier refund_type in the refunds API payload was going as "instant". But it needs to be "scheduled". So we have removed refund_type parameter in the refunds API payload which will by default take "scheduled".
- For a successful payment , initiate a refund 
- The refunds API payload should not contain refunds_type 
- The refund_type should be by default "scheduled"

chore: refund type removed from refunds api

---

src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res

Totp settings not showing up in profile section

fix:  totp extra settings not visible in profile page

---

src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformance.res
src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRate.res
src/screens/Analytics/PerformanceMonitor/GaugeChart/GaugeChartPerformance.res
src/screens/Analytics/PerformanceMonitor/PerformanceMonitor.res
src/screens/Analytics/PerformanceMonitor/PerformanceMonitorEntity.res
src/screens/Analytics/PerformanceMonitor/PerformanceMonitorTypes.res
src/screens/Analytics/PerformanceMonitor/PerformanceUtils.res
src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformance.res
src/screens/Analytics/PerformanceMonitor/TablePerformance/TablePerformance.res

Exclude user dropout status i.e payment_method_awaited from 
1. payment distrubution by status graph in performance monitor analytics 
2. payment failure rate graph
The payment distribution by status graphs should not contains payment_method_awaited status

feat: performance monitor exclude filter value

---

src/entryPoints/AuthModule/AuthWrapper.res
src/entryPoints/AuthModule/SSOAuth/SSODecisionScreen.res

while rendering the home screen the height of the loading screen was not full screen

fix: loading page height before login screen 

---

src/screens/Connectors/ConnectorUtils.res
src/screens/ThreeDsProcessors/ThreeDsConnectorList.res

Added a separate list for threeds authenticators for prod . 
Enable the threeds_authenticator feature flag and the is_live_mode flag. Under the Connectors section, there will be a dedicated area for the 3DS authenticator, which should include Netcetera.

feat: Netcetera to prod

---

src/components/HSwitchSingleStatTableWidget.res
src/screens/Analytics/PaymentsAnalytics/SmartRetryAnalytics.res

smart retry tool tip info was not visible on hover and this pr will fix that
on hover info icon of smart retry tile on payment analytics page the info should show up like in screen shot shown

fix: smart retries tooltip bug fix

---

src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res

global search result page dispute table ordering similar to other table in the page 
col in order `DisputeId-> PaymentId -> DisputeStatus -> DisputeAmount -> Currency -> Connector`
col in order `DisputeId-> PaymentId -> DisputeStatus -> DisputeAmount -> Currency -> Connector`

fix: disputes table col ordering

---

src/screens/Payouts/PayoutsList.res

increased the table items limit from 10 to 20 items per page and fixed the page items ordering fix when the items per page is selected as 15
navigate to diff page and the items order should be in sequence , data should load 20 items per page max

fix: payouts pagination order fix

---

src/screens/Home/ProdIntent/ProdVerifyModalUtils.res

In production intent email form the website input we accept mandatorily asks for http:// which is not necessary
websites tests 
Valid: https://calendar.google.com, http://www.example.com, example.co.uk, sub.example.com, example.com
Invalid: -example.com, example-.com, example.com-

fix: prod intent website regex change

---

src/components/Paginator.res

table items per page is not used to show `20` prev but now it will start showing cause most of the table have limit set to 20

fix: pagination rows per page selector fix

---

src/entryPoints/HyperSwitchApp.res
src/entryPoints/SidebarValues.res
src/screens/Hooks/OMPSwitchHooks.res
src/screens/OMPSwitch/ProfileSwitch.res
src/screens/UserManagement/UserRevamp/ListRoles.res

Issues covered in this PR : 
1. Remove Create custom role button for profile level users.
2. API Keys should be disabled for profile level users.
3. Issue when you switch from payment details to different profile at the top
1. Remove Create custom role button for profile level users.
- create a profile level user 
- go to users section , under the roles tab 
- create custom role button should be disabled 
2. API Keys should be disabled for profile level users.
-  create a profile level user 
- In the sidebar you cannot see api keys 
4. Issue when you switch from payment details to different profile at the top

fix: user management revamp bugs

---

src/components/priority-logics/AddPLGateway.res

Fixxed the volume based routing issue where connector name vanishes after a node delete 
whe we remove the item from list , the rest of the nodes should display the connector label as it

fix: volume based routing fix

---

src/screens/Analytics/Analytics.res
src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalytics.res
src/screens/Analytics/DisputeAnalytics/DisputeAnalytics.res
src/screens/Analytics/HSAnalyticsUtils.res
src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
src/screens/Analytics/RefundsAnalytics/RefundsAnalytics.res
src/screens/Analytics/SystemMetrics/SystemMetricsAnalytics.res
src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalytics.res
src/screens/OMPSwitch/OMPSwitchHelper.res
src/screens/OMPSwitch/OMPSwitchUtils.res

Views change in analytics & payment operations
1. Payment ops
2. analytics 
Closes change 3 & 4 of #1448 
1. Payment ops should have views with current mercant id and profile id 
2. Analytics should have view switch with current org , merchant and profile

fix: omp views changes in analytics & ops

---

src/screens/APIUtils/APIUtils.res
src/screens/Hooks/OMPSwitchHooks.res
src/screens/OMPSwitch/OMPSwitchTypes.res
src/screens/UserManagement/UserRevamp/ListRoles.res
src/screens/UserManagement/UserRevamp/ListUsers.res
src/screens/UserManagement/UserRevamp/UserManagementHelper.res
src/screens/UserManagement/UserRevamp/UserManagementLanding.res
src/screens/UserManagement/UserRevamp/UserManagementTypes.res
src/screens/UserManagement/UserRevamp/UserManagementUtils.res

View changes in users module
Closes change 1 of https://github.com/juspay/hyperswitch-control-center/issues/1448
User management page have views [My Team , Organisation , Merchant , Profile]. 
My team will consist of all the values for that user based on entity of the user 
Organisation,Merchant & Profile will contain the users at entity organisation , merchant and profile respectively

fix: list users views in users page

---

src/screens/NewAnalytics/NewAnalyticsUtils.res

this function will. take the response for graphs and generate the missing points for days or weeks or hours 
the line chart should have a complete time range on the x axis with missing points leading to 0

chore: empty points generator function for graphs

---

config/config.toml
src/entryPoints/FeatureFlagUtils.res
src/screens/Order/Orders.res

applied feature flag for transactions view
to enable and disable views as per requirement
feature flag for transactionView introduced

chore: transaction view feature flag

---

src/components/Table.res
src/components/TableUtils.res

- undesired click on customize columns fixed
- height issue fix of table cell
before
after
bugfix
- click on the customise columns button cells, it does take you to payments page
- add CustomerID column, height of table cell remains same as before,

fix: table customise column bugfix

---

src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptEntity.res
src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentEntity.res
src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTableEntity.res
src/screens/Disputes/DisputesEntity.res
src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
src/screens/Order/OrderEntity.res
src/screens/Payouts/PayoutsEntity.res
src/screens/Refunds/RefundEntity.res
src/screens/ThreeDsProcessors/ThreeDsProcessorHome.res

remove redundant code & remove compiler warning
connect three ds connector
check the connected connector
three dots previously seen in top right corner are removed

chore: removed compiler warning and threeds comp change

---

src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
src/entryPoints/HyperSwitchApp.res
src/entryPoints/SidebarValues.res
src/screens/APIUtils/APIUtils.res
src/screens/Sidebar/Sidebar.res
src/screens/UserManagement/UserRevamp/NewUserInvitationForm.res
src/screens/UserManagement/UserRevamp/UserManagementHelper.res
src/screens/UserManagement/UserRevamp/UserManagementTypes.res
src/screens/UserManagement/UserRevamp/UserManagementUtils.res
src/utils/HyperSwitchUtils.res

Internal entity removal from frontend
Create a internal user and check for that particular user to test all the flows

chore: internal entity removal

---

src/screens/APIUtils/APIUtils.res

bug fix
go to users > check invited user > manager user > resend invite
the api will not return any error

fix: fix resend invite api url

---

src/screens/Connectors/ConnectorUIUtils/PaymentMethod.res

pm auth processor is disabled -> then sidebar for pm authentication should not be shown in bank debit pmts
bugfix
now sidebar is not shown if pm auth is disabled

fix: check for disabled pm auth connector

---

src/components/TableUtils.res

Removed no text-wrap class from card cells to keep content wrapped, improving layout consistency.
Improving layout consistency.
Tested the code manually in payment cards.

fix: table text-wrap removed

---

src/entryPoints/HyperSwitchApp.res

userpermission data not getting set 
bugfix
connectors api is being called on refresh

fix: api not getting called due to user permission data not updated

---

src/screens/Developer/APIKeys/DeveloperUtils.res
src/screens/Developer/PaymentSettings/PaymentSettings.res
src/screens/Developer/PaymentSettings/PaymentSettingsListEntity.res
src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
src/screens/Settings/HSwitchSettingTypes.res
src/screens/Settings/MerchantAccountUtils.res
src/utils/LogicUtils.res
src/utils/Mappers/BusinessProfileMapper.res

New fields added in payment settings page
- Auto retries enabled
- Maximum number of Auto retries
product requirement
Go to Payment Settings
Able to see Auto Retries toggle 
On enabling the toggle, user can enter Maximum number of auto-retries desired (validation for the field - values only accepted from 1 to 5)

feat: add auto retries in payment settings

---

src/screens/Connectors/ConnectorPreview.res

The connector status is updated on making desired changes and the same are reflected in the connectors list.
After Resolution :
https://github.com/user-attachments/assets/e89fea31-5d48-4c12-83ba-2df64531ce2a
The changes are done for better user experience and ensuring consistency among different views. 
Attached video.

fix: Update status of connector ( Disable / Enable )

---

src/screens/APIUtils/APIUtils.res

Url Name issue for create custom role fix
Go to users and click on create custom role . It shouldn't break

fix: url name issue in create custom role page

---

src/screens/PMAuthenticationProcessor/PMAuthenticationConnectorList.res
src/screens/TaxProcessor/TaxProcessorList.res
src/screens/ThreeDsProcessors/ThreeDsConnectorList.res

Connected processor list should be on top in pm-auth , tax processors and 3ds connectors with no search boxes.
BEFORE: 
AFTER:
For better user experience and accessibility.
Tested display as shown in desc.

fix: connected list on top in  3DS connectors  , tax processors and PM authentication processors

---

src/screens/Hooks/OMPSwitchHooks.res
src/screens/Settings/BusinessDetails.res

Disabled Edit for Profile level users in business details.
https://github.com/user-attachments/assets/af6cf365-c55e-4f24-9e1a-0c761839318a
To enforce stricter access control within our application. Profile-level users typically have limited permissions that do not include the ability to modify business-critical information. This enhances security , maintains consistency and improves user experience.
I checked the enable/disable of edit business section between different level users. It was working as expected.

fix: disable edit for profile level user (Business section)

---

src/container/MerchantAccountContainer.res

Initially we were conditionally not rendering merchant id and publishable key on home at user profile view but the credentials were shown in merchant account api response. Ideally profile user should not know any credentials and information regarding merchant.
To enforce stricter access control.
I checked the if the profile view was rendering without any display of credentials .

fix: merchant account credentials not shown in profile view

---

src/screens/Order/OrderUIUtils.res

Card-network was disabled from FE . This will enable the card-network filter from FE
card-network should be visible in FE in filters

fix: changes to enable card-network

---

src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res
src/screens/Disputes/DisputeTypes.res
src/screens/Disputes/DisputesEntity.res
src/screens/Disputes/DisputesUtils.res

Removing dispute stage as dispute status is sufficient to indicate the status.
Dispute stage not needed
checked it in the dispute view table.

fix: remove dispute stage col

---

src/entryPoints/AuthModule/Common/CommonAuthTypes.res
src/entryPoints/AuthModule/Common/CommonAuthUtils.res
src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
src/entryPoints/AuthModule/TwoFaAuth/TwoFaLanding.res
src/screens/Settings/HSwitchProfile/TwoFaSettings/ModifyTwoFaSettings.res
src/screens/Settings/HSwitchProfile/TwoFaSettings/RegenerateRC.res
src/screens/Settings/HSwitchProfile/TwoFaSettings/ResetTotp.res
src/screens/Settings/HSwitchProfile/TwoFaSettings/TwoFaHelper.res

The maximum number of incorrect attempts allowed after logging in has been introduced. Previously, there was no limit, but now after exceeding the limit, there will be a cool-down period of 5 minutes for TOTP and 10 minutes for recovery codes. This will come when user tries to change its totp or regenerate-recovery code 
Max attempts reached for totp :
Max attempts reached for recovery code :
If both recovery code and totp is reached :
- Setup totp for a user 
- Go to profile section and change totp 
- In the verify modal , try wrong totp for 4 times after 5th time the above max attempts reached for totp modal should appear 
- Max attempts reached for recovery-code should give the above max attempts reached for recovery code modal should appear
- Same should happen for regenerate recovery …

chore: TwoFa restriction after multiple failed attempts after logging in

---

CHANGELOG.md
src/hooks/AuthHooks.res
webpack.dev.js

This PR disabled cookies from frontend for the upcoming changes regarding making frontend and backend url same
Additionally, it sets proxy in webpack.dev.js to test the above thing in local
Sign in to dashboard
Check in Application Storage under cookies 
Cookies will not be set after this change

chore: disable cookies from frontend

---

src/components/DateRangeCompareFields.res
src/components/DateRangeHelper.res

display comparision values in the ISO format in the button text 
the comparision date should be ISO format but should send to BE in the UTC format

fix: compare filter date display fix to ISO format

---

src/screens/NewAnalytics/Graphs/LineGraph/LineGraphTypes.res
src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionTypes.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedTypes.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res

diaplying the analytics amount metrics in USD in FE
primary changes will be picking the `_usd` key in the place of normal amount key 
eg `total_smart_retried_amount` -> `total_smart_retried_amount_usd` etc
the amount values which is displayed in FE will be in USD for overview `total payments` and `payment processe` module when amount is selected

feat: analytics payment processed currency conversion

---

src/screens/NewAnalytics/Graphs/LineGraph/LineGraphTypes.res
src/screens/NewAnalytics/Graphs/LineGraph/LineGraphUtils.res
src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionHelper.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionTypes.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedTypes.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res

fixes new analytics ui bug fixes 
- Currency should be shown in correct denomination (divide by 100) when amount is being shown
- Labels for success and failure distributions are not present for some of the group by - payment_method_type
- Currency symbol like USD, INR or $, etc whenever amount is being showed
- Percentage should be restricted to max 100% in rate related graphs
bug fixed in this tickets are 
- Currency should be shown in correct denomination (divide by 100) when amount is being shown
- Labels for success and failure distributions are not present for some of the group by - payment_method_type
- Currency symbol like USD, INR or $, etc whenever amount is being showed
- Percentage should be restricted to max 100% in rate related graphs

fix: analytics revamp bug fixes

---

src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res

changed the sanky flow chart and the modification in the nodes values calcualtion formaulas 
for response 
<pre>
{
normalSuccess: 50,
normalFailure: 30,
smartRetriedSuccess: 15,
smartRetriedFailure: 15,
cancelled: 10,
pending: 10,
partialRefunded: 10,
refunded: 45,
disputed: 10,
pmAwaited: 4,
customerAwaited: 4,
merchantAwaited: 1,
confirmationAwaited: 1,
}
</pre>
with smart retry 
without smart retry 
base flow chart 
the flow chart should match the payment list data

feat: sanky flow chart change

---

src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
src/entryPoints/AuthModule/TwoFaAuth/TwoFaLanding.res
src/entryPoints/AuthModule/TwoFaAuth/TwoFaTypes.res
src/entryPoints/AuthModule/TwoFaAuth/TwoFaUtils.res

Earlier there was no way to force two-fa . With this change there will be a way to force two-fa if backend sends is-skippable as false 
- force-two-factor-auth from backend as false 
then there should be a skip button available in FE 
- force-two-factor-auth from backend as true 
then there should not be a skip button available in FE 
Tested in local

feat: add functionality to force two-fa

---

src/entryPoints/AuthModule/Common/CommonAuthForm.res
src/entryPoints/AuthModule/Common/CommonAuthTypes.res
src/entryPoints/AuthModule/Common/CommonAuthUtils.res
src/entryPoints/AuthModule/Common/CommonInputFields.res
src/entryPoints/AuthModule/TwoFaAuth/TwoFaUtils.res
src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
src/utils/Modal.res

It implements conditional availability for the "Change Password" feature based on the status of the Email feature flag. When the Email feature flag is turned off, the "Change Password" option is now available to users, allowing password updates without email-based actions.
Allowing password updates without email dependency
Tested it locally with backend.

feat: change password feature

---

src/components/DateRangeCompareFields.res
src/container/NewAnalyticsContainer.res
src/screens/NewAnalytics/NewAnalyticsUtils.res

things fixed in this pr
the compare date range matjing the primary date range 
showing proper predifined date label selected

fix: compare date range component minor fixes 

---

src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res

the payment count for same date range from list api vs payment life cycle api 
when u select the same date range in operatiin tab and analytics tab the payment initiated should be same

fix: sankey flow chart count fix

---

src/screens/UserManagement/UserRevamp/NewUserInvitationForm.res
src/screens/UserManagement/UserRevamp/UserInfo.res

Earlier custom roles description showed role id instead of role name.
**Before :** 
**After :**
This PR updates the role description to show the role name instead of the role ID for better clarity. It helps make the UI more user-friendly and easier to understand.
Tested locally and working as expected

fix: show role name for custom roles

---

src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphTypes.res
src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphUtils.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res

sankey values normalizarion so when values are too high the graph wont break and ui fixes 
before
after 
sakey shoudn't break for large values and on date range the graph shoud't break

fix: sankey ui fixes

---

src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res

USD string fix when count is selected 
the USD string should show only when amount tab is selected and for Count is should not come

fix: payment processed USD string fix

---

.githooks/commit-msg
.github/workflows/ci.yml
.github/workflows/cypress-test.yml
.github/workflows/eslint-check.yml
.github/workflows/pr-title-spell-check.yml
.github/workflows/release-stable-version.yml

For Open Source contribution we were not able to run checks as it's showing unable to checkout the code.
Will test this after merging the PR and make sure it works.

ci: git checkout token for open source contribution

---

src/components/DateRangeCompareFields.res
src/components/DateRangeField.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res

fix: analytics minor bugs

---

src/screens/PayoutRouting/PayoutRoutingConfigure.res
src/screens/Routing/DefaultRouting.res
src/screens/Routing/RoutingConfigure.res
src/screens/Routing/VolumeSplitRouting.res
src/screens/RoutingRevamp/AdvancedRouting.res

- Show only payment processors in default fallback routing connectors list
- indicate the disabled connectors in connector dropdown and list in payment and payout routing in Workflow module
Connect any connector other than payment connector
Go to Workflow > Routing > Default Fallback > Manage
Connectors other than Payment connectors are not visible in list
Now disable any connected payment connected and check the list again

Fix: Filter routing connector list

---

src/screens/OMPSwitch/ProfileSwitch.res

bugfix in case of user does not have access to connector module, list profile api is not getting called due to condition of non empty business profiles
bugfix
- check list profile api should call at least once on homepage to load profile dropdown options
- it might get called a couple of times due to dependency on other variables

fix: list profile api

---

src/screens/SDKPayment/WebSDK.res

Removing this unnecessary api call in sdk page
Before
After
- go to sdk page
- try making a test payment 
- it should be successful

chore: removing api call not required on sdk page

---

src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res

fixed count mismatch in payment processed module graph in header vs query data
the header value and the total of query that i.e points should be same

fix: payment prosecces count fix

---

src/screens/Analytics/AnalyticsUtils.res
src/screens/Analytics/DisputeAnalytics/DisputeAnalytics.res
src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
src/screens/Analytics/RefundsAnalytics/RefundsAnalytics.res

filtering out the sessionized metircs for refunds and disputes page 
the metrics list shoud not contain sessionized metiics in refunds and dispute analytics page

fix: filter sessionized metrics

---

src/screens/Routing/DefaultRouting.res

chaneged the connector list extraction chanes for default routing for new change and fallback for older code as well
the connector list for default routing should come for old code as well as new changes as well where coneecotr list inside profile id object or connector list direct array

fix: default routing connector list extraction changes

---

src/screens/Disputes/DisputesUtils.res
src/screens/HSwitchRemoteFilter.res
src/screens/Order/OrderUIUtils.res
src/screens/Payouts/PayoutsUtils.res
src/screens/Refunds/RefundUtils.res

- Fixed issue where removing the customer_id filter cleared all other applied filters.
- The change ensures that only the customer_id filter is removed, while the other filters remain applied and visible.
https://github.com/user-attachments/assets/18c6cb3d-73c2-4eb9-8c26-90899f65412c
User experience
Attached video

fix: Customer ID remove key

---

src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionTypes.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res

picking from refunds amount from metadat rather than from query data for correct value display 
the refunds amoutn displayed in the analytics overview section should be in USD

fix: analytics refunds amount usd conversion fix

---

src/screens/UserManagement/UserRevamp/UserUtils.res

Addition of max limit of 10 invites at a time in frontend.

feat: frontend invite limit

---

src/screens/SDKPayment/SDKPage.res

error on sdk page when no payment connector connected but other category connector are connected
current 
fixed
- connect any connector other than payment connector (eg FRM, 3ds)
- go to sdk page to try a test payment
- it should show connect a new connector screen

fix: error on sdk page when no payment connector connected

---

src/screens/OMPSwitch/MerchantSwitch.res
src/screens/OMPSwitch/OrgSwitch.res
src/screens/OMPSwitch/ProfileSwitch.res
src/utils/GlobalVars.res

currently on profile switch user is always redirected to home page
with this change - on profile switch the user will land on the same subsection link 
for org and merchant switch 
currently: for the url that does not exist it shows error page and for others it goes to  home page
with this change: same behaviour as on profile switch (will land on the same subsection link )
suppose url is `/payments/pay_eHqoQH7t3efEazeiEXu2/pro_IJGV7MaFtoDvI9P5Ri0h` it will be redirected to `/payments`
and so on, this ensures that user does not see any error and still remains under same module after switch
improving user experience
- observe url changes on different pages on profile switch

chore: url path after OMP switch

---

src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayIntegration.res

enabling web domain for fiuu processor 
- go to connectors
- start configure fiuu
- on payment methods page, go to apple pay
- able to proceed with web domain

chore: enable we domain for fiuu apple pay

---

src/screens/Analytics/GlobalSearch/GlobalSearchBar.res

checking if the user has a acess to view rhe filetrs suggestions on global search 
if the uer doesn't have a acess he should be shown a suggestions for filters selected

fix: global search filters access check

---

src/components/Table.res

No visibility of horizontal scrollbar in tables scroll leading to confusion.
Better User experience
Tested locally: In Payments , refunds and Disputes , when adding more columns than can fit in the visible area, a horizontal scrollbar appears.

fix: Horizontal Scrollbar to Tables

---

src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphTypes.res
src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphUtils.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleTypes.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res

changed the sankey flow chart and tooltip advancements 
with smart retry 
without smart retry 
the numerbers of diff nodes whould be same to of in payments page

fix: sanky flow chart change and tooltip ui advancements 

---

src/screens/Sidebar/Sidebar.res

PR resolves the issue with active selection in the sidebar by ensuring the correct item is highlighted when navigating. 
After changes - 
It improves the handling of active states for better visual feedback and good user experience.
Tested locally

fix: sidebar-active-selection-resolution

---

src/utils/DateRangeUtils.res

date range compare component the end time won't overlap with prumary date range start value now 
the date range should remains between primary and secondary and the end time of compare should not overlap with start time of primary date

fix: date range compare component end time fix 00:00 to 59.59

---

src/screens/Analytics/RefundsAnalytics/RefundsAnalyticsEntity.res

cause of BE default group by currency the old analytics overview section was breaking cause of two reponse object , fixed this issue in this pr 
the values should be populated for all the metrics in the refunds analytics page

fix: refunds amount overview fix

---

src/entryPoints/HyperSwitchApp.res
src/screens/Sidebar/Sidebar.res

- org and merchant list api do not support internal user, therefore hiding these dropdown for internal user

chore: hiding org merchant dropdown for internal user

---

src/entryPoints/SidebarValues.res
src/screens/NewAnalytics/NewAnalyticsTypes.res
src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPayments.res
src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPaymentsTypes.res
src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPaymentsUtils.res
src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res

failure reasons table for payment analytics

feat: paymants failure reasons

---

src/screens/Connectors/ConnectorWalletDetails/Paze/PazeIntegration.res
src/screens/Transaction/CommonFilters/AmountFilter/AmountFilter.res
src/screens/Transaction/CommonFilters/AmountFilter/AmountFilterUtils.res

Floating-point precision in the amount filter by ensuring consistent scaling and encoding of values. 
Selection of same option again.
https://github.com/user-attachments/assets/93ccdb3e-256c-42ab-aebd-178feff165f4
User experience.
Locally.

fix: Amount Filter bug

---

src/components/form/PillInput.res

Addition of a new input type which takes multiple input values convert them to array of pills.
https://github.com/user-attachments/assets/7ee5e12a-ce34-4653-9806-cc320ce8b605
Requirement in other task and  provides a more intuitive way to display and manage multiple values in the UI.
Locally.

feat: new pill input type

---

src/container/MerchantAccountContainer.res
src/entryPoints/HyperSwitchApp.res
src/entryPoints/SidebarValues.res
src/screens/Recon/ReconModule.res
src/screens/Recon/ReconTypes.res
src/screens/Recon/ReconUtils.res

- URL changes for recon 
- Changes for handling iframe logout
- Enable recon for a merchant 
- The iframe should be loaded
- when the iframe session is expired the dashboard should be logged out

fix: handle recon-iframe logout in dashboard

---

src/screens/UserManagement/UserRevamp/InviteMember.res
src/screens/UserManagement/UserRevamp/UserManagementHelper.res
src/screens/UserManagement/UserRevamp/UserManagementUtils.res

- showing loader modal while switch merchant and profile in invite users
- displaying "All Profiles" by default  in profile dropdown to indicate merchant level user being invited
https://github.com/user-attachments/assets/5233c3b3-d810-4494-a010-9ca04aa96d38
- changes visible in invite users page

chore: invite users enhancement

---

src/entryPoints/SidebarValues.res

Fix for get production access component not visible in sandbox
Before:
After:

fix: Get production access component visibility in sandbox

---

src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
src/screens/Analytics/GlobalSearch/GlobalSearchBarHelper.res

rather then showing error text multiple free text it will show up during typing itself if the multiple free text is detected and the second free text is not a filter keyword 
when u enter a multiple frree text the waring will be displyed and this warning will show up only if the free text is not a filter

chore: global search free text handling

---

src/context/ThemeProvider.res

textcolor to not get picked from primary but to be picked from default.
UI
Locally

fix: font color primary

---

src/screens/OMPSwitch/MerchantSwitch.res
src/screens/OMPSwitch/OMPSwitchHelper.res
src/screens/OMPSwitch/ProfileSwitch.res

- limit the width of profile and merchant dropdowns
- org base comp word limit incresed to show ellipsis
current
new
current
new
current
new
improving ui
check the ui changes as in desc

chore: limit unusually large width of dropdown

---

src/screens/OMPSwitch/OMPSwitchHelper.res
src/screens/OMPSwitch/OrgSwitch.res

- this is specific change made to alter the view of org dropdown in case of tenant admin with more than 20 orgs because currently the api is only sending 20 org so there is discrepency that the. selected org might not be present in the org dropdown, hence removed the org dropdown as discussed particularly for  this case
org dropdown in case of tenant admin having more than 20 orgs
check the org comp in home page for tenant admin

chore: org dropdown for tenant admin

---

config/config.toml
src/APIUtils/APIUtils.res
src/components/AdvancedSearchComponent.res
src/components/AdvancedSearchModal.res
src/components/DynamicChart.res
src/components/DynamicSingleStat.res
src/components/DynamicTable.res
src/components/custom-icons/LottieFiles.res
src/context/ChartContext.res
src/context/SingleStatContext.res
src/context/ThemeProvider.res
src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
src/entryPoints/FeatureFlagUtils.res
src/hooks/AuthHooks.res
src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
src/screens/Hooks/OMPSwitchHooks.res
src/screens/MixpanelHook.res
src/screens/OMPSwitch/OMPSwitchHelper.res
src/screens/SDKPayment/WebSDK.res
src/screens/Settings/ComplianceCertificates/Compliance.res
webpack.dev.js

Introduced a `force_cookies` feature flag, defaulting to false. When enabled (true), it enforces cookie usage; when disabled (false), cookies are not enforced.
Recent multitenancy updates in Sandbox encountered several bugs due to same-origin credential issues. Adding conditional cookie enforcement via the force_cookies flag addresses these issues and improve handling.
On being false, cookies weren't sent in the request.
Have to explicitly make it true for development and integ.

chore: conditional enforcement of cookies

---

src/components/NoDataFound.res
src/screens/Payouts/PayoutsList.res
src/screens/Transaction/Disputes/Disputes.res
src/screens/Transaction/Order/Orders.res
src/screens/Transaction/Refunds/Refund.res

Now when button is clicked , endtime becomes the previous start time without a day being subtracted.
Additionally refactored code to make it more generic.
https://github.com/user-attachments/assets/f2f20b3f-6c11-4857-aef8-19b8896f2c7a

fix: Fixed extend date button functionality

---

src/screens/Developer/PaymentSettings/PaymentSettings.res

Need to show only authentication processors in the dropdown list
Via local UI in Click to Pay - previously every processor mcs_id was coming now only authentication processors coming.

chore: filter authentication processor

---

src/APIUtils/APIUtils.res
src/screens/Customers/Customers.res

pagination implementation for customer table, `currently api response doesn't contains total_count so the total numbers of pages has been set to 50 for now` and user can change between the pages 
while changing the page diff cuotomers will be listed out in the table, and the max number of pages is 50 and table can have no data but still can contain number of pages displyaed is 50

feat: customer table pagination

---

CHANGELOG.md
src/components/Graphs/SankyGraph/SankeyGraphUtils.res
src/screens/NewAnalytics/NewAnalyticsFilters/NewAnalyticsFiltersUtils.res
src/screens/NewAnalytics/NewAnalyticsHelper.res
src/screens/NewAnalytics/NewAnalyticsTypes.res
src/screens/NewAnalytics/NewAnalyticsUtils.res
src/screens/NewAnalytics/NewRefundsAnalytics/FailureReasonsRefunds/FailureReasonsRefundsUtils.res
src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSectionUtils.res
src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedUtils.res
src/screens/NewAnalytics/NewRefundsAnalytics/RefundsReasons/RefundsReasonsUtils.res
src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPaymentsUtils.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
src/utils/LogicUtils.res
src/utils/LogicUtilsTypes.res

Moved value formatter to LogicUtils
https://github.com/juspay/hyperswitch-control-center/issues/2097
Refactoring PR make sure the NewAnalytics have amount in the format as earlier.

refactor: Value formatter moved to LogicUtils

---

src/screens/SDKPayment/SDKPage.res

`go to payment` button after successful payment through sdk dashboard including the profile, merchant and org id to the redirection link 
after a successful payment done though sdk in dashboard the `go to payment` button should redirect to that payments details page

fix: sdk go to payment button redirection fix

---

public/hyperswitch/module.js

Initially the themes css was getting appended to the dom multiple times. The changes allow to just replace with the last updated values.
Locally

fix: Refactoring append themes css logic

---

src/screens/Customers/Customers.res

api calls will fertch 50 items per api calls 
each calls should retrun a 50 items and when u select show 50 results per page it should display all 50 rows

chore: customer list limit increased from 10 to 50

---

src/container/NewAnalyticsContainer.res
src/screens/HSwitchRemoteFilter.res

analytics currency filter modification 
the currency applied in insights page shoudn't effect the old paymants and refunds analytics pages

fix: analytics filters init set function modification

---

src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res

added granularity options for refunds tab analytics
on diff granularity options selected the number of points on graph should change and on diff time range the granuality options should also change [tabs displayed]

feat: granularity options for refunds tab analytics

---

public/hyperswitch/icons/solid.svg
src/components/DatePicker.res
src/components/LoadedTable.res
src/components/PopUpConfirm.res
src/entryPoints/AuthModule/TwoFaAuth/TotpRecoveryCodes.res
src/entryPoints/SidebarValues.res
src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ApplePay/ApplePayIntegrationHelper.res
src/screens/Connectors/PaymentProcessor/ConnectorPreview.res
src/screens/Developer/APIKeys/PublishableAndHashKeySection.res
src/screens/Developer/PaymentSettings/PaymentSettings.res
src/screens/Helpers/HelperComponents.res
src/screens/OMPSwitch/OMPSwitchHelper.res
src/screens/OMPSwitch/OrgSwitch.res
src/screens/Routing/ActiveRouting.res
src/screens/Routing/CustomModal.res
src/screens/RoutingRevamp/AdvancedRouting.res
src/screens/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
src/screens/Settings/HSwitchProfile/TwoFaSettings/RegenerateRC.res
src/screens/Sidebar/OrgSidebar.res
src/screens/Transaction/Order/HSwitchOrderUtils.res
tailwind.config.js

Fixes Dashboard UI redesign issues.
#2160 
UI
Locally

fix: Dashboard redesign ui issues

---

src/entryPoints/SidebarValues.res
src/screens/Sidebar/OrgSidebar.res

Used the last two characters of `orgID` as the `orgTile` display when orgName is not provided.
Previously, the list of organizations appeared inconsistent and shuffled when orgName was missing. This change ensures a more structured and recognizable indexing approach.
Locally

fix: org indexes logic fix

---

src/entryPoints/AuthModule/PreLoginModule/AuthSelect.res
src/screens/Developer/PaymentSettings/PaymentSettings.res
src/screens/Routing/ActiveRouting.res

changed payment settings update button and auth select to full width button
Locally
When we invite a user, the user gets email to join the community. Then the button Continue with Password should be full width button.
When we navigate to payment settings the update button should be with center aligned.

fix: Button issues fix in payment settings and auth select

---

src/screens/Payouts/PayoutsEntity.res
src/screens/Payouts/PayoutsList.res
src/screens/Payouts/ShowPayout.res

Payout details page wasn't being displayed.
https://github.com/user-attachments/assets/eeeb62e7-91c0-4a4d-afbd-6c74eac6fa49
Bug fix
Locally

fix: payout details page display

---

src/screens/OMPSwitch/OMPSwitchHelper.res

If the names of the profile and merchant were more than 20 then it was showing functional ellipses causing overflow on opening. Added overflow scroll to view large names and stop overflow.
After changes:
https://github.com/user-attachments/assets/dbe53ce5-f748-4b92-b276-c04723cd72c3
UI 
Locally

fix: Overflowing merchant profile names in dropdowns

---

src/screens/Sidebar/OrgSidebar.res
src/screens/UserManagement/UserRevamp/ListUsers.res

While switching the organization, the organization list order is maintained without shifting active organization to the top of the organization list.
Requirement
Locally
https://github.com/user-attachments/assets/f999de4b-c3d8-4ba2-8339-41cf82b6822a

fix: maintaining org sidebar list order

---

src/screens/Connectors/FraudAndRisk/FRMSelect.res

Even though there's a payment connectors beign configued the from page still shows defailt landing page 
the frm should show frm connectors when there one or more payment connectors are beign configured

fix: fraud and risk connector list bug fix

---

src/IntelligentRoutingScreens/IntelligentRoutingHelper.res
src/components/Graphs/ColumnGraph/ColumnGraphUtils.res

Column graphs listing the tooltip values 
Locally
Before:
After recon v2 configuration the column graph tooltip was displaying two values 
After: It will be based on the points list

fix: column graph tooltip formatter listing

---

src/screens/OMPSwitch/OMPSwitchHelper.res

Edit and copy button in mobile is visible only when clicking on the merchant drop down item. As there is no hover in mobile. It should be visible by default instead of click.
Locally

fix: show edit and copy icon in MP dropdowns mobile

---

src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsConfigureRetry.res

added the tool tip for configure retry pages 
the tooltip should show for configure retry pages

chore: configure retry tooltip text

---

src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res
src/screens/Connectors/ConnectorUtils.res

made the chargebee webhooks details as required field 
the billing connector chargebee page should show the webhooks details page as required and the next

chore: made chargebee webhooks details field as required

---

src/entryPoints/HyperSwitchApp.res

Logo was getting stretched out. Fixed scaling
UI
Locally

fix: logo aspect ratio

---

src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalytics.res

Removed Profile level Generate reports as Auth Analytics is only having merchant level analytics.
Will add this back when backend is ready with the profile level analytics.
For making UI consistent
Locally via removing the dropdown only merchant report API was getting called.

chore: remove profile level report - auth analytics

---

src/screens/PayoutRouting/PayoutRoutingConfigure.res
src/screens/Routing/DefaultRouting/DefaultRouting.res
src/screens/Routing/RoutingConfigure.res

Connector labels weren't visible for the payout routing default fallback. After changes:
Bugfix
Locally

fix: Payout routing default fallback connector label

---

src/screens/Routing/AdvancedRouting/AdvancedRoutingUtils.res
src/screens/Routing/RoutingUtils.res

In rule-based routing, the pre-populated month was incorrect.
After : 
- Sign-in to a orchestration account 
- under Workflows , navigate to routing 
- Under routing choose Advanced routing , the pre-populated description should have the current month

fix: rule based routing month issue in description

---

src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res

Add closes icon in merchant select modal , on click it will redirect back to current modules home page 
- create multiple merchant for another product apart from Orchestrator For rg: Vault
- Click on Vault from Sidebar , merchant dropdown will appear 
- Click on close icon , it should redirect back to current active product's home page eg: Orchestration home

fix: close icon on merchant select modal

---

src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
src/Recon/ReconScreens/ReconReports/ReconReports.res
src/entryPoints/HyperSwitchApp.res
src/entryPoints/SidebarValues.res

Removed get production access for v2 products 
For V2 merchant : 
For V1 merchant : 
for v2 merchants get production access should not come in sidebar as well as in product banner

chore: removed production access for v2 products

---

src/Recon/ReconScreens/ReconReports/ReconReportsList.res
src/Recon/ReconScreens/ReconReports/ShowAllReports.res
src/components/InputFields.resi
src/screens/Analytics/HSAnalyticsUtils.res

`OK` and `More Details` button is not visible in the `all` recon reports tab for 13 inch screen laptop.
https://github.com/juspay/hyperswitch-control-center/issues/2760
Locally

fix: recon ui issues in 13 inch screen

---

src/screens/Connectors/PaymentProcessor/Common/CommonConnectorHelper.res
src/screens/Connectors/PaymentProcessor/Common/CommonConnectorTypes.res
src/screens/Connectors/PaymentProcessor/Common/CommonConnectorUtils.res
src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ConnectorMetaDataUtils.res

Number type input addition for connector metadata fields 
Cannot test as it is a chore chage

chore: number type input for connector metadata

---

src/screens/Settings/HSwitchSettingTypes.res
src/screens/Settings/MerchantAccountUtils.res

Validation check for three_ds_requestor_app_url field for
1. mobile deeplinks (e.g. merchantapp://auth/success?transactionId=1234567890) 
2. http/https links
https://github.com/user-attachments/assets/e9745ece-5069-4284-920e-b37d5852df5e
Currently, empty strings and invalid request URLs are being populated in three_ds_requestor_app_url field. This PR resolves that.
attached video

fix: threeds app url validation

---

src/screens/OMPSwitch/OMPSwitchHelper.res
src/screens/Sidebar/OrgSidebar.res

empty page issue on omp dropdown item click
- open dashboard 
- click on any omp item click 
- should not redirect to empty page

fix: empty page issue on omp dropdown item click

---

src/screens/Transaction/Order/OrderRefundForm.res

Errors dict was getting populated even if address and email fields not present. 
Bugfix
Locally

fix: refunds disable/enable in operations

---

src/screens/Analytics/Logs/LogUtils/AuditLogUI.res

Fixed tab switching issue in log viewer. When navigating between different log entries, the active tab is now correctly reset to "Log Details" to ensure proper content display.
Bugfix
Locally
https://github.com/user-attachments/assets/a277c05d-7da3-463d-b817-f232153ed772

fix: Logs in payments details

---

src/screens/Connectors/ConnectorUtils.res

If metadata is not there , by default we will send empty dict instead of null.
bugfix
Locally

fix: connector metadata default

---

src/screens/Analytics/Logs/LogUtils/ApiDetailsComponent.res
src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
src/screens/Analytics/Logs/LogUtils/LogTypes.res

- request and response data was shown interchanged in audit trail of payments details 
- fixed log details state to contain correct data under request and request
- initially request and response were stored but while displaying response was being shown with request header 
- checked that request and response are displayed correctly under webhooks in audit trail

fix: webhooks request response data interchange fix

---

src/components/TimeInput.res
src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
src/screens/GenerateReports/DownloadReportModal.res
src/screens/Transaction/Order/OrderUIUtils.res

1. Dates not carried over for Generate Reports in Payments section
2. Time selection as a filter for Generate reports, Payments view
3. Added scroll bar for overflow values in the dashboard response
Locally
https://github.com/user-attachments/assets/0252e1ca-dc57-48ee-b167-c35f0ab1849d

chore: added time selection for payments and reports

---

src/screens/Analytics/Logs/LogUtils/LogTypes.res

- rename webhooks heading in audit trail from Request to Event Data
locally, check screenshot

fix: rename webhooks request heading to event data

---

src/components/Filter.res
src/screens/ConfigurePMTs/paymentMethodList.res

- In configure PMT if you select / deselect a filter (not apply a filter) PMT table refreshes for no reason.
- Select a filter, go to next page, click "Add filters" and you can select the same filter.
- Select a filter, go to some page (ex: 40), select another filter, even if there are results it doesn't redirect to first page OR redirects to last page
- Filters are overlapped with table headers
https://github.com/juspay/hyperswitch-control-center/issues/1061
Locally
https://github.com/user-attachments/assets/58f36a48-2440-4cee-9832-91f7554af4a9

fix: configure pmts filter issues

---

src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalytics.res

In the NewAuthenticationAnalytics component where the setAllFilters function in the DynamicFilter component was not updating when remoteFilters changed
Problem: getFilters API Call When dimensions Is Empty and Same Key for Some and None case:
If dimensions was empty (e.g., due to an API giving response with not None in loadInfo), Rendering the Component with Key 0 in `NewAuthenticationAnalytics` and eventually after loading the dimensions with correct value, the key doesn't change as it is still in the Some case which is not mounting the `DynamicFilter` component again to set allFilters.
Locally

fix: new authentication analytics key and dimensions changes

---

src/screens/UserManagement/UserRevamp/InviteMember.res

- currently no event exist for sending user invite button click, that is added in this PR

chore: added send invite mixpanel event

---

src/components/FilterSelectBox.res
src/screens/Connectors/ConnectorUtils.res
src/screens/HSwitchRemoteFilter.res
src/screens/Payouts/PayoutsList.res
src/screens/Transaction/Disputes/DisputesUtils.res
src/screens/Transaction/Refunds/RefundUtils.res

https://github.com/user-attachments/assets/f7119b4c-c275-4d75-99e4-90e4e248df96
Operations tab should have only payment and threeds processors in the connector filter list

fix: All types of connectors showing in operations connector filter

---

src/screens/Developer/APIKeys/DeveloperUtils.res
src/screens/Developer/APIKeys/KeyManagement.res

Throwing 500 error when adding long key and description for api key generation
https://github.com/juspay/hyperswitch-control-center/issues/2136
Locally
https://github.com/user-attachments/assets/82887556-9c10-4ffa-af03-1b3434a017c5

fix: added validation for the api keys

---

src/components/CustomCharts/HighchartTimeSeriesChart.res
src/components/CustomCharts/LineChartUtils.res
src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformanceUtils.res
src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRateUtils.res
src/screens/Analytics/PerformanceMonitor/GaugeChart/GaugeChartPerformanceUtils.res
src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformanceUtils.res

changed the old analytics graphs font style to Inter Display
the data displayed on the graph should have the same font

fix: changed old analytics graph font style to InterDisplay

---

cypress/e2e/3-operations/paymentOperations.cy.js

Payment Operations date range selection in cypress test is checking with the single digit date, so when the date is from 1st to 9th it will be 1, 2, ... 9 but in the website we have date range with 2 digits 01, 02, 03, ... 09

test: payment operations date checking with 2 digits

---

.github/workflows/pr-label.yml

- pr-label workflow currently removed all the labels and adds the `closed` 
- instead it should only remove `S-waiting-on-review` and add `closed`

chore: updated pr label workflow

---

src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res

recovery Processor Reference ID empty value validation check for billing connector onboarding flow 
then the Processor Reference ID is empty the next button should be disabled

fix: recovery Processor Reference ID empty value validation check

---

src/screens/SDKPayment/PreviewSection/SDKPayment.res
src/screens/SDKPayment/PreviewSection/WebSDK.res
src/screens/SDKPayment/SDKHelper/TestCredentials.res

Style issue the page was not scollable for multiple saved cards

chore: style issues for scrolling sdk

---

src/components/InputFields.res
src/components/InputFields.resi
src/components/SelectBox.res
src/container/InsightsAnalyticsContainer.res
src/screens/NewAnalytics/InsightsAnalyticsFilters/InsightsAnalyticsFilters.res
src/screens/NewAnalytics/InsightsContainerUtils.res
src/screens/NewAnalytics/InsightsUtils.res
src/screens/OMPSwitch/OMPSwitchHelper.res

1. Disabled Currency Filter for Refunds
- The "All Currencies (Converted to USD*)" filter is now disabled in the Refunds section, as currency conversion is not applicable here.
2. Disabled OMP View Filter
- The "View Data for" dropdown is now disabled with hyperswitch_test as the selected (and grayed-out) option, since data remains static regardless of selection.
3. Updated sample date range to 4th September – 3rd October across all graphs and tables to ensure consistency.
4. Updated Sample Data for Graph Accuracy
refunds.json and payments.json have been updated with more realistic, non-linear values to reflect actual behavior.
Tables and graphs are now consistent and accurate based on the revised data files.
5. Aligned Date Ranges Across Graphs and Tables
Sample Data are as follows: ( …

fix: Analytics sample fixes

---

cypress/e2e/6-workflow/PaymentRouting.cy.js
src/screens/Routing/AuthRateRouting/AuthRateRouting.res
src/screens/Routing/CustomModal.res

save rule option hidden for auth rate routing because toggle api will activate the configuration also

chore: disable create configuration flow only for auth rate routing

---

src/screens/Routing/AdvancedRouting/AdvancedRoutingUtils.res

- generateStatement methods was adding empty condition array in the rules while generating payload 
- removed that empty condition array since that was causing backend to behave unusually while calculating and applying rules
- check surcharge update api, it should not have empty condition array in the statements inside rules

fix: routing rule generated statements to exclude empty condition

---

src/components/DateRangeCompareFields.res
src/components/DateRangeField.res
src/components/DateRangeHelper.res
src/utils/DateRangeUtils.res
tailwind.config.js

- to resolve #3123 
13 inch:
14 inch:
16 inch:
- Also added a highlight for the selected option to improve visibility and enhance the user experience.
UX
Locally

fix: Custom daterange selector overlap with sidebar

---

src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalytics.res
src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsHelper.res
src/screens/NewAnalytics/NewAuthenticationAnalytics/SCAExemptionAnalytics/SCAExemptionAnalyticsUtils.res

This PR fixes the Sankey chart data calculation logic to ensure accurate mapping of authentication and exemption statuses. It also includes minor UI adjustments to font size and the "+ Add Filters" button is now hidden when sample data is in use to avoid confusion. Also fixed a latency issue where old data was briefly shown when switching from sample data to real data.
I have tested it in local setup.

fix: correct 3DS sankey data calculation and ui

---

src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsHelper.res
src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
src/Recon/ReconScreens/ReconReports/ReconReportsHelper.res
src/screens/OMPSwitch/OMPSwitchHelper.res

The nd_gray-100 wasn't present before in tailwind and components that had border-nd_gray-100 were actually using default border color. The expected color for profile border is nd_gray-150.
Also OMP chart icon should use theme colors so that it can fit fill in all scenarios.
UI Fix
locally

fix: theme colors for sidebar ompchart and border fix

---

src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
src/screens/OMPSwitch/MerchantSwitch.res

- showing a prefilled merchant name in create merchant modal, with `productName_randomString` format

chore: display prefilled merchant name in create merchant modal

---

src/screens/Home/ProdIntent/GetProductionAccess.res

- prod access form not visible due to product type change

fix: prod access form not visible

---

src/screens/Analytics/Logs/LogUtils/AuditLogUI.res

audit log mismatch with the active selected log type 
the log deytails in the right side shoudl match with the active selected log details

fix: audit logs order and log details mismatch fix

---

src/screens/Transaction/Order/HSwitchOrderUtils.res
src/screens/Transaction/Order/ShowOrder.res

Remove sync button in the payment detail page if it is a terminal status, Cancelled and Expired are the terminal payment intent statuses
https://github.com/juspay/hyperswitch-control-center/issues/3468
Locally

chore: remove sync for terminal payment intent status

---

src/screens/NewAnalytics/Insights/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
src/screens/NewAnalytics/Insights/PaymentAnalytics/InsightsPaymentAnalyticsUtils.res
src/screens/NewAnalytics/Insights/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
src/screens/NewAnalytics/Insights/SmartRetryAnalytics/FailureSmartRetryDistribution/FailureSmartRetryDistribution.res
src/screens/NewAnalytics/Insights/SmartRetryAnalytics/SuccessfulSmartRetryDistribution/SuccessfulSmartRetryDistribution.res

For all filters , metrics were repeating as group by api wasn't being called.
But for sample data created a aggregator function to aggregate repetitive values:
The change is for ->
Payments -> Successful Payments Distribution -> Authentication Type
Payments -> Failed Payments Distribution -> Authentication Type
Smart retries -> Successful Distribution of Smart Retry Payments -> Authentication Type
Smart retries -> Failed Distribution of Smart Retry Payments -> Authentication Type
Bugfix
Locally

fix: sample analytics group by bugfix

---

src/ReconEngine/ReconEngineApp/ReconEngineSidebarValues.res
src/ReconEngine/ReconEngineScreens/ReconEngineAccounts/ReconEngineAccountsTransformation/ReconEngineAccountsTransformationComponents/ReconEngineAccountTransformationConfigDetails.res
src/ReconEngine/ReconEngineScreens/ReconEngineAccounts/ReconEngineAccountsTransformation/ReconEngineAccountsTransformationHelper.res
src/entryPoints/ProductUtils.res

Renamed Reconcilliation Engine to Reconciliation
Sidebar should say Data instead of Accounts
Transformation config cards text no break
https://github.com/juspay/hyperswitch-control-center/issues/3589
Locally

fix: reconciliation engine naming and style changes

---

src/ReconEngine/ReconEngineScreens/ReconEngineAccounts/ReconEngineAccountsOverview/ReconEngineAccountsOverviewComponents/ReconEngineAccountsOverviewTransformedEntries.res
src/ReconEngine/ReconEngineScreens/ReconEngineAccounts/ReconEngineAccountsOverview/ReconEngineAccountsOverviewHelper.res
src/ReconEngine/ReconEngineScreens/ReconEngineAccounts/ReconEngineAccountsSources/ReconEngineAccountsSourcesComponents/ReconEngineAccountSourceConfigDetails.res
src/ReconEngine/ReconEngineScreens/ReconEngineAccounts/ReconEngineAccountsTransformedEntries/ReconEngineAccountsTransformedEntries.res
src/ReconEngine/ReconEngineScreens/ReconEngineAccounts/ReconEngineAccountsTransformedEntries/ReconEngineAccountsTransformedEntriesComponents/ReconEngineAccountsTransformedEntriesOverviewCards.res

count the `staging_entries` based on the `transformation_history_id`
Locally

chore: count the `staging_entries` based on the `transformation_history_id`
